package com.app.fku.itopya.fonksiyon.impl;

import com.app.fku.genel.fonksiyon.service.GenelService;
import com.app.fku.genel.fonksiyon.service.LogService;
import com.app.fku.genel.model.GenelUrunModel;
import com.app.fku.itopya.entity.ItopyaKategori;
import com.app.fku.itopya.entity.ItopyaTelegramConf;
import com.app.fku.itopya.fonksiyon.service.ItopyaGenelService;
import com.app.fku.itopya.fonksiyon.service.ItopyaUrunToplaFonksiyon;
import com.app.fku.itopya.repository.ItopyaTelegramConfRepository;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.Node;
import org.jsoup.select.Elements;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;

@Service
public class ItopyaUrunToplaFonksiyonImpl implements ItopyaUrunToplaFonksiyon {

    @Autowired
    ItopyaGenelService itopyaGenelService;

    @Autowired
    GenelService genelService;

    @Autowired
    LogService logService;

    @Autowired
    ItopyaTelegramConfRepository itopyaTelegramConfRepository;

    @Override
    public HashMap<String, GenelUrunModel> menudenUrunBul(ItopyaKategori itopyaKategori, Integer page, Integer maxPage, HashMap<String, GenelUrunModel> urunHashMap, HashMap<String, GenelUrunModel> yeniUrunHashMap, boolean ilkMi) throws IOException, InterruptedException {
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm");
        NumberFormat nf = new DecimalFormat("#0.00");
        try {
            Document itopyaDoc = null;
            for (int i = 1; i > 0; i++) {
                try {
                    itopyaDoc = itopyaGenelService.urleGit(itopyaKategori.getSayfaAdresi() + "&sayfa=" + page);
                    if (itopyaDoc == null) {
                        logService.itopyaLogYaz("itopyaDoc null (Captcha) 1 " + itopyaKategori.getKategoriAdi() + " " + page);
                    } else {
                        break;
                    }
                } catch (Exception e) {
                    logService.itopyaLogYaz("itopyaDoc null (Captcha) 2 " + itopyaKategori.getKategoriAdi() + " " + page);
                }
                Thread.sleep(10000L);
            }

            if (maxPage == null) {
                String maxPageStr = itopyaDoc.getElementsByClass("page-info").get(0).childNodes().get(3).childNodes().get(0).toString().trim().split("/")[1];
                maxPage = new Integer(maxPageStr.trim());
            }

            Element urunListDiv = itopyaDoc.getElementById("productList");
            Elements urunElementList = urunListDiv.getElementsByClass("product");
            for (Element urunElement: urunElementList) {
                String id = urunElement.getElementsByClass("product-header").get(0).childNodes().get(1).attributes().get("href").toString().split("_")[1].trim();

                String urunAdi = urunElement.getElementsByClass("product-body").get(0).childNodes().get(1).childNodes().get(0).toString();
                String fiyatStr = urunElement.getElementsByClass("price").get(0).childNodes().get(1).childNodes().get(0).toString().split(",")[0].replace(".", "");

                Long yeniFiyat = new Long(fiyatStr);
                GenelUrunModel genelUrunModel = urunHashMap.get(id);

                if (genelUrunModel == null) {
                    //yeni gelmiş ürün
                    GenelUrunModel yeniUrunModel = new GenelUrunModel();
                    yeniUrunModel.setModel(urunAdi);
                    yeniUrunModel.setEskiFiyat(yeniFiyat);
                    yeniUrunModel.setSonMesajTarihi(new Date());
                    //yeniUrunHashMap.put(id, yeniUrunModel);
                    urunHashMap.put(id, yeniUrunModel);
                    if (!ilkMi) {
                        //mesaj at
                        String akakceLink = urunAdi.replace(" ", "%2B");
                        akakceLink = akakceLink.replace("+", "");

                        String mesaj = "" +
                                "YENİ ÜRÜN%0A" +
                                "Kategori Adı: " + itopyaKategori.getKategoriAdi() + "%0A" +
                                "Ürün Adı: " + urunAdi + "%0A" +
                                "Yeni Fiyat: " + nf.format(yeniFiyat) + "%0A" +
                                "Ürün Link:" + "https://www.itopya.com/eminkayabasi_" + id + "%0A" +
                                "Tarih: " + sdf.format(new Date()) + "%0A" +
                                "Akakçe Link:https://www.akakce.com/arama/?q=" + akakceLink + " %0A " +
                                "***Generated By Emin KAYABASI***";

                        telegramMesajGonder(mesaj, itopyaKategori, id, 0L, yeniFiyat);
                    }
                } else {
                    //zaten var olan ürün
                    if (yeniFiyat < genelUrunModel.getEskiFiyat()) {
                        //mesaj at
                        String akakceLink = urunAdi.replace(" ", "%2B");
                        akakceLink = akakceLink.replace("+", "");

                        Long indirim = genelUrunModel.getEskiFiyat() - yeniFiyat;
                        Long indYuzde = 100 * indirim / genelUrunModel.getEskiFiyat();

                        if (indYuzde > itopyaKategori.getIndirimYuzdesi()) {
                            String mesaj = "" +
                                    "Kategori Adı: " + itopyaKategori.getKategoriAdi() + "%0A" +
                                    "Ürün Adı: " + urunAdi + "%0A" +
                                    "Eski Fiyat: " + nf.format(genelUrunModel.getEskiFiyat()) + "%0A" +
                                    "Yeni Fiyat: " + nf.format(yeniFiyat) + "%0A" +
                                    "İndirim Yüzde: " + nf.format(indYuzde) + "%0A" +
                                    "İndirim: " + nf.format(indirim) + "%0A" +
                                    "Ürün Link:" + "https://www.itopya.com/eminkayabasi_" + id + "%0A" +
                                    "Tarih: " + sdf.format(new Date()) + "%0A" +
                                    "Akakçe Link:https://www.akakce.com/arama/?q=" + akakceLink + " %0A " +
                                    "***Generated By Emin KAYABASI***";

                            telegramMesajGonder(mesaj, itopyaKategori, id, indYuzde, yeniFiyat);
                            genelUrunModel.setSonMesajTarihi(new Date());
                        }
                    }
                    genelUrunModel.setEskiFiyat(yeniFiyat);
                    //yeniUrunHashMap.put(id, genelUrunModel);
                    urunHashMap.put(id, genelUrunModel);
                }
            }

            if (maxPage != null) {
                if (page < maxPage) {
                    menudenUrunBul(itopyaKategori, page + 1, maxPage, urunHashMap, yeniUrunHashMap, ilkMi);
                }
            }
//            return yeniUrunHashMap;
            return urunHashMap;
        } catch (Exception e) {
            logService.itopyaLogYaz("Itopya Hata Kategori:" + itopyaKategori.getKategoriAdi() + " - Sayfa: " + page);
            Thread.sleep(10000L);
            return urunHashMap;
        }
    }

    private void telegramMesajGonder(String mesaj, ItopyaKategori itopyaKategori, String urunId, Long indYuzde, Long fiyat) throws IOException, InterruptedException {
        List<ItopyaTelegramConf> itopyaTelegramConfList = itopyaTelegramConfRepository.findByItopyaKategori(itopyaKategori);

        for (ItopyaTelegramConf itopyaTelegramConf: itopyaTelegramConfList) {//fkumesajbot
            genelService.telegramMesajGonder(mesaj, itopyaTelegramConf.getTelegramChatId(), urunId, "5326840199:AAEWApODrhD-pxplBYAgUIRMo2FI565mNfM");
        }

        if (indYuzde > 40) {
            genelService.telegramBombaGonder(mesaj, urunId);
        }

        if (fiyat <= 50) {
            genelService.telegramFiyatHatasiGonder(mesaj, urunId);
        }
    }
}
