package com.app.fku.galerycristal.fonksiyon.impl;

import com.app.fku.galerycristal.entity.GcKategori;
import com.app.fku.galerycristal.entity.GcTelegramConf;
import com.app.fku.galerycristal.fonksiyon.service.GcEkranOkumaService;
import com.app.fku.galerycristal.fonksiyon.service.GcGenelService;
import com.app.fku.galerycristal.repository.GcTelegramConfRepository;
import com.app.fku.genel.enums.EvetHayirEnum;
import com.app.fku.genel.fonksiyon.service.GenelService;
import com.app.fku.genel.fonksiyon.service.LogService;
import com.app.fku.genel.model.GenelUrunModel;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.concurrent.TimeUnit;

@Service
public class GcEkranOkumaServiceImpl implements GcEkranOkumaService {

    @Autowired
    GenelService genelService;

    @Autowired
    LogService logService;

    @Autowired
    GcGenelService gcGenelService;

    @Autowired
    GcTelegramConfRepository gcTelegramConfRepository;

    @Override
    public HashMap<String, GenelUrunModel> kategoriIleUrunBul(GcKategori gcKategori, int hataCount, HashMap<String, GenelUrunModel> urunHashMap, HashMap<String, GenelUrunModel> yeniUrunHashMap, boolean ilkMi) throws InterruptedException {
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm");
        NumberFormat nf = new DecimalFormat("#0.00");

        if (yeniUrunHashMap == null) {
            yeniUrunHashMap = new HashMap<>();
        }

        try {
            Document gcDoc = null;
            for (int i = 1; i > 0; i++) {
                gcDoc = gcGenelService.urleGit(gcKategori.getSayfaAdresi());

                if (gcDoc == null) {
                    logService.gcLogYaz("GC Hata aAA");
                    Thread.sleep(4000);
                } else {
                    break;
                }
            }

            Elements productElements = gcDoc.getElementsByClass("productItem");
            for (Element element: productElements) {
                Attributes productAttr = element.attributes();
                String gcNo = productAttr.get("id");
                String model = element.childNodes().get(3).attributes().get("content");
                String urunUrl = "https://www.gallerycrystal.com.tr/" + element.childNodes().get(1).attributes().get("content");

                GenelUrunModel genelUrunModel = urunHashMap.get(gcNo);
                String fiyatStr = element.getElementsByClass("proRowAct").get(0).childNodes().get(3).attributes().get("content").split("\\.")[0].trim();

                 Double yeniFiyat = Double.valueOf(fiyatStr);

                 if (genelUrunModel == null) {
                    //yeni gelmiş ürün
                     GenelUrunModel yeniUrunModel = new GenelUrunModel();
                     yeniUrunModel.setModel(model);
                     yeniUrunModel.setFiyat(yeniFiyat);
                     yeniUrunModel.setMinFiyat(yeniFiyat);
                     yeniUrunModel.setMinFiyatTarihi(new Date());
                     yeniUrunModel.setSonMesajTarihi(new Date());
                     yeniUrunHashMap.put(gcNo, yeniUrunModel);

                    if (!ilkMi) {
                        String akakceLink = model.replace(" ", "%2B");
                        akakceLink = akakceLink.replace("+", "");

                        String mesaj = "" +
                                gcKategori.getKategoriAdi() + "%0A" +
                                "YENİ ÜRÜN%0A" +
                                "Ürün Adı: " + model + "%0A" +
                                "Yeni Fiyat: " + nf.format(yeniFiyat) + "%0A" +
                                "Ürün Link:" + urunUrl + "%0A" +
                                "Tarih: " + sdf.format(new Date()) + "%0A" +
                                "Akakçe Link:https://www.akakce.com/arama/?q=" + akakceLink + " %0A " +
                                "***Generated By Emin KAYABASI***";

                        telegramMesajGonder(mesaj, gcKategori, model, 0L, yeniFiyat.longValue());
                    }
                } else {
                    //zaten var olan ürün
                    if (yeniFiyat < genelUrunModel.getFiyat()) {
                        //mesaj at
                        long diff = new Date().getTime() - genelUrunModel.getSonMesajTarihi().getTime();
                        long minutes = TimeUnit.MILLISECONDS.toMinutes(diff);
                        if (minutes > 10) {
                            String akakceLink = model.replace(" ", "%2B");
                            akakceLink = akakceLink.replace("+", "");

                            Double indirim = genelUrunModel.getFiyat() - yeniFiyat;
                            Double indYuzde = 100 * indirim / genelUrunModel.getFiyat();
                            String mesaj = "" +
                                    gcKategori.getKategoriAdi() + "%0A" +
                                    "Ürün Adı: " + model + "%0A" +
                                    "Eski Fiyat: " + nf.format(genelUrunModel.getFiyat()) + "%0A" +
                                    "Yeni Fiyat: " + nf.format(yeniFiyat) + "%0A" +
                                    "Min Fiyat: " + nf.format(genelUrunModel.getMinFiyat()) + "%0A" +
                                    "Min Fiyat Tarihi: " + sdf.format(genelUrunModel.getMinFiyatTarihi()) + "%0A" +
                                    "İndirim Yüzde: " + nf.format(indYuzde) + "%0A" +
                                    "İndirim: " + nf.format(indirim) + "%0A" +
                                    "Ürün Link:" + urunUrl + "%0A" +
                                    "Tarih: " + sdf.format(new Date()) + "%0A" +
                                    "Akakçe Link:https://www.akakce.com/arama/?q=" + akakceLink + " %0A " +
                                    "***Generated By Emin KAYABASI***";

                            telegramMesajGonder(mesaj, gcKategori, model, indYuzde.longValue(), yeniFiyat.longValue());
                            genelUrunModel.setSonMesajTarihi(new Date());
                        }

                    }
                     genelUrunModel.setFiyat(yeniFiyat);
                     if (yeniFiyat < genelUrunModel.getMinFiyat()) {
                         genelUrunModel.setMinFiyat(yeniFiyat);
                         genelUrunModel.setMinFiyatTarihi(new Date());
                     }

                     yeniUrunHashMap.put(gcNo, genelUrunModel);
                }
            }

            return yeniUrunHashMap;
        } catch (Exception e) {
            logService.gcLogYaz("GC Hata");
            Thread.sleep(3000L);
            return urunHashMap;
        }
    }

    private void telegramMesajGonder(String mesaj, GcKategori gcKategori, String urunId, Long indYuzde, Long fiyat) throws IOException, InterruptedException {
        List<GcTelegramConf> gcTelegramConfList = gcTelegramConfRepository.findByGcKategori(gcKategori);

        for (GcTelegramConf gcTelegramConf : gcTelegramConfList) {
            genelService.telegramMesajGonder(mesaj, gcTelegramConf.getTelegramId(), urunId, "5825214508:AAFtR93SN_JLYTIraHT_5SxU0un0Of0qY4k");
        }
    }
}