package com.app.fku.amazonx.fonksiyon.impl;

import com.app.fku.amazonx.fonksiyon.service.AmazonxService;
import com.app.fku.amazonx.model.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectWriter;
import org.json.JSONException;
import org.jsoup.Connection;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.net.URLConnection;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;

@Service
public class AmazonxServiceImpl implements AmazonxService {

    private static final List<YeniAmazonLinkModel> urlList = new ArrayList<>();

    public void sorgula() throws InterruptedException {
        urlList.add(new YeniAmazonLinkModel("A33AVAJ2PDY3EV", "A1UNQM1SR2CHM", 17452328031L, "Philips", "AgAATUgwRgIhAJV9jgKphd2pSXyM9tJFVqU8WrIFd7e3s2YvLKVuMzDsAiEAh3dsLmsNuLdBxfGdKOKQTNqpyftV0nzbmqJupfp4FgACdjEAAQBQAY5EXT98VNUjAnYxN/ekCafAndDkqO7yhC2p5+RFiET7BAjYxRMwVZpXjukAAAAIBnJldGFpbA1hbWF6b24uY29tLnRyBXRyLVRSVFJZAaECAAMLAQEDAAAEAAA="));//Amazon Philips
        for (; ; ) {
            try {
                anaislem();
            } catch (Exception e) {
                System.out.println("hata geldi amz");
            }
        }
    }

    private static void anaislem() throws InterruptedException, IOException {
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy hh:mm");

        HashMap<String, AmazonUrunModel> urunHashMap = new HashMap<>();
        System.out.println(sdf.format(new Date()) + " Toplam Ürün: " + urunHashMap.size());

        boolean ilkTur = true;
        for (; ; ) {
            System.out.println(sdf.format(new Date()) + " Toplu Ürün Adedi: " + urunHashMap.size());

            List<AmazonUrunModel> topluUrunList = new ArrayList<>();
            for (YeniAmazonLinkModel linkModel : urlList) {
                List<String> asinList = asinListDoldur();//readJsonFromUrl1(linkModel);
                int count = asinList.size() / 24;
                count = count + 1;

                int anaSayac = 0;
                for (int i = 0; i < count; i++) {
                    List<String> newAsinList = new ArrayList<>();
                    for (int tmpSayac = 0; tmpSayac < 24; tmpSayac++) {
                        if (anaSayac == asinList.size()) {
                            break;
                        }
                        newAsinList.add(asinList.get(anaSayac));
                        anaSayac = anaSayac + 1;
                    }

                    AmazonResponse2Model amazonResponse2Model = readJsonFromUrl2(linkModel, newAsinList);
                    for (AmazonResponseProductModel amazonResponseProductModel : amazonResponse2Model.getProducts()) {
                        try {
                            if (!((LinkedHashMap) amazonResponseProductModel.getBuyingOptions().get(0).getMerchant()).get("merchantName").equals("Amazon.com.tr")) {
                                continue;
                            }
                        } catch (Exception e) {
                            continue;
                        }

                        AmazonUrunModel amazonUrunModel = new AmazonUrunModel();
                        amazonUrunModel.setKategoriAdi(linkModel.getKeywords());
                        amazonUrunModel.setAsin(amazonResponseProductModel.getAsin());
                        amazonUrunModel.setUrunAdi(amazonResponseProductModel.getTitle().getDisplayString());

                        try {
                            Double pd = (Double) ((LinkedHashMap) ((LinkedHashMap) ((LinkedHashMap) ((LinkedHashMap) amazonResponseProductModel.getBuyingOptions().get(0).getPrice()).get("priceToPay")).get("moneyValueOrRange")).get("value")).get("amount");
                            amazonUrunModel.setFiyat(pd.longValue());
                        } catch (Exception e) {
                            continue;
                        }

                        try {
                            if (((LinkedHashMap) ((ArrayList) ((LinkedHashMap) ((LinkedHashMap) ((LinkedHashMap) ((LinkedHashMap) amazonResponseProductModel.getBuyingOptions().get(0).getPromotionsUnified()).get("summary")).get("shortMessage")).get("message")).get("fragments")).get(0)).get("text").equals("Ödeme esnasında ")) {
                                Double sepetIndirimi = (Double) ((LinkedHashMap) ((LinkedHashMap) ((ArrayList) ((LinkedHashMap) ((LinkedHashMap) ((LinkedHashMap) ((LinkedHashMap) amazonResponseProductModel.getBuyingOptions().get(0).getPromotionsUnified()).get("summary")).get("shortMessage")).get("message")).get("fragments")).get(1)).get("money")).get("amount");
                                amazonUrunModel.setFiyat(amazonUrunModel.getFiyat() - sepetIndirimi.longValue());
                            }
                        } catch (Exception e) {
                            //System.out.println("promotionUnified Hata: " + amazonUrunModel.getAsin());
                        }

                        topluUrunList.add(amazonUrunModel);
                    }
                }
            }

            for (AmazonUrunModel amazonUrunModel : topluUrunList) {
                AmazonUrunModel eskiAmazonUrunModel = urunHashMap.get(amazonUrunModel.getAsin());
                if (eskiAmazonUrunModel != null) {
                    //Önceden var olan ürün, fiyat kontrol et
                    if (amazonUrunModel.getFiyat() < eskiAmazonUrunModel.getFiyat() && !ilkTur) {
                        String mesaj = "" +
                                "İndirim%0A" +
                                "" + amazonUrunModel.getKategoriAdi() + "%0A" +
                                "" + amazonUrunModel.getUrunAdi() + "%0A" +
                                "Eski Fiyat: " + eskiAmazonUrunModel.getFiyat() + "%0A" +
                                "Yeni Fiyat: " + amazonUrunModel.getFiyat() + "%0A" +
                                "Link:https://www.amazon.com.tr/dp/" + amazonUrunModel.getAsin();

                        telegramMesajGonder(mesaj, "-4123427362");
                        telegramMesajGonder(mesaj, "-4110725323");
                    }
                } else {
                    if (!ilkTur) {
                        //Ürün yeni gelmiş direk mesaj at
                        String mesaj = "" +
                                "Yeni Ürün%0A" +
                                "" + amazonUrunModel.getKategoriAdi() + "%0A" +
                                "" + amazonUrunModel.getUrunAdi() + "%0A" +
                                "Fiyat: " + amazonUrunModel.getFiyat() + "%0A" +
                                "Link:https://www.amazon.com.tr/dp/" + amazonUrunModel.getAsin();

                        telegramMesajGonder(mesaj, "-4123427362");
                        telegramMesajGonder(mesaj, "-4110725323");
                    }
                }

                urunHashMap.put(amazonUrunModel.getAsin(), amazonUrunModel);
            }

            ilkTur = false;
            System.out.println("Amazon: " + urunHashMap.size() + "\n");
        }
    }

    public static Document readJsonFromUrl(String url) throws IOException, JSONException {
        //RandomString gen = new RandomString(8, ThreadLocalRandom.current());
        //url = url + "&" + gen.nextString() + "=" + gen.nextString();

        return Jsoup
                .connect(url)
                .userAgent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36")
                .referrer("http://www.google.com")
                .timeout(12000)
                .followRedirects(true)
                .ignoreContentType(true)
                .get();
    }

    public static AmazonResponse2Model readJsonFromUrl2(YeniAmazonLinkModel linkModel, List<String> asinList) throws IOException, JSONException, InterruptedException {

        HashMap<String, String> headerMap = new HashMap<>();
        headerMap.put("authority", "www.amazon.com.tr");
        headerMap.put("accept", "application/json, text/plain, */*");
        headerMap.put("content-type", "application/json; charset=UTF-8");
        headerMap.put("origin", "https://www.amazon.com.tr");
        headerMap.put("user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36");

        AmazonRequestModel amazonRequestModel = new AmazonRequestModel();
        AmazonRequestSubModel amazonRequestSubModel = new AmazonRequestSubModel();
        amazonRequestSubModel.setObfuscatedMarketplaceId(linkModel.getObfuscatedMarketplaceId());
        amazonRequestSubModel.setObfuscatedMerchantId(linkModel.getObfuscatedMerchantId());
        amazonRequestSubModel.setLanguage("tr-TR");
        amazonRequestSubModel.setCurrency("TRY");
        amazonRequestSubModel.setSlateToken(linkModel.getSlateToken());
        AmazonRequestSub2Model amazonRequestSub2Model = new AmazonRequestSub2Model();
        List<String> terms = new ArrayList<>();
        terms.add(linkModel.getKeywords());
        amazonRequestSub2Model.setTerms(terms);
        List<String> isSearch = new ArrayList<>();
        isSearch.add("true");
        amazonRequestSub2Model.setIsSearch(isSearch);
        amazonRequestSubModel.setQueryParameterMap(amazonRequestSub2Model);
        amazonRequestModel.setRequestContext(amazonRequestSubModel);
        amazonRequestModel.setASINList(asinList);
        amazonRequestModel.setEndpoint("ajax-data");

        ObjectWriter ow = new ObjectMapper().writer().withDefaultPrettyPrinter();
        String jsonStr = ow.writeValueAsString(amazonRequestModel);

        String json = null;
        for (; ; ) {
            try {
                json = Jsoup
                        .connect("https://www.amazon.com.tr/juvec")
                        .userAgent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36")
                        .headers(headerMap)
                        .method(Connection.Method.POST)
                        .requestBody(jsonStr)
                        .ignoreContentType(true)
                        .execute()
                        .body();

                if (json != null && !json.equals("")) {
                    break;
                }
            } catch (Exception e) {
                int randomNum = ThreadLocalRandom.current().nextInt(1100, 5300);
                Thread.sleep(randomNum);
                System.out.println("Amazon readJsonFromUrl2 hata : " + linkModel.getKeywords());
            }
        }

        json = json.replaceAll("&&&", ",");

        ObjectMapper mapper = new ObjectMapper();
        AmazonResponse2Model amazonResponseModel = mapper.readValue(json, AmazonResponse2Model.class);
        return amazonResponseModel;
    }


    public static void telegramMesajGonder(String mesaj, String chatId) throws IOException, InterruptedException {
        //System.out.println(urunId + " " + chatId + " mesaj gönderdim. " + urunId);
        mesaj = mesaj.replace(" h", "xh");
        mesaj = mesaj.replace(" H", "xh");
        mesaj = mesaj.replace("ş", "s");
        mesaj = mesaj.replace("Ş", "s");
        mesaj = mesaj.replace("ı", "i");
        mesaj = mesaj.replace("İ", "i");
        mesaj = mesaj.replace("ğ", "g");
        mesaj = mesaj.replace("Ğ", "g");
        mesaj = mesaj.replace("ö", "o");
        mesaj = mesaj.replace("Ö", "o");
        mesaj = mesaj.replace("Ç", "c");
        mesaj = mesaj.replace("ç", "c");
        mesaj = mesaj.replace("Ü", "u");
        mesaj = mesaj.replace("ü", "u");
        mesaj = mesaj.replace("&", "");
        String urlString = "https://api.telegram.org/bot%s/sendMessage?chat_id=%s&text=%s";    //Add Telegram token//
        String token = "5326840199:AAEWApODrhD-pxplBYAgUIRMo2FI565mNfM";
        String text = mesaj;
        urlString = String.format(urlString, token, chatId, text);
        try {
            URL url = new URL(urlString);
            URLConnection conn = url.openConnection();
            InputStream is = conn.getInputStream();
        } catch (IOException e) {
            e.printStackTrace();
            Thread.sleep(10000L);
        }
    }

    public static List<String> asinListDoldur() {
        List<String> asinList = new ArrayList<>();

        //Philips Kahve Makinesi
        asinList.add("B07MMSHC4R");//Philips EP2220
        asinList.add("B07MMSWP78");//Philips EP2231
        asinList.add("B0CRDM9HY1");//Philips EP2331
        //asinList.add("B07M8J529L");//Philips EP3246
        asinList.add("B0CDCFH17J");//Philips EP3347
        asinList.add("B08CBJVNCV");//Philips EP4346
        asinList.add("B0BRNF848D");//Philips EP5443
        asinList.add("B08CBJ8W9W");//Philips EP5447
        //Philips Kahve Makinesi

        //Philips Fritöz
        //asinList.add("B0CD2KVVRC");//Philips HD9243
        asinList.add("B08KGDS4CZ");//Philips HD9252
        asinList.add("B08D9HYZMS");//Philips HD9252-2
        //asinList.add("B0BJNW9H1K");//Philips HD9255
        //asinList.add("B0BZ16HDK9");//Philips HD9257
        //asinList.add("B0BWRSF3CJ");//Philips HD9285
        asinList.add("B0767DNSMH");//Philips HD9650
        asinList.add("B092DS3RDL");//Philips HD9867
        asinList.add("B09TBGR44Q");//Philips HD9870
        asinList.add("B0C1P59N7Y");//Philips HD9875
        asinList.add("B0BWKLDVDQ");//Philips HD9880
        //Philips Fritöz

        //asinList.add("B0C2877GJS");//Philips QP2824

        //Karaca Hamur Mak
        asinList.add("B09M7PQ82X");//Karaca Mastermaid Chef Stand Mikser Red 1500W 5 Lt
        asinList.add("B09S1LGXTF");//Karaca Mastermaid Chef Stand Mikser Sarı 1500W 5 Lt
        asinList.add("B0BZ4NZDZN");//Karaca Mastermaid Chef Stand Mikser Mavi 1500W 5 Lt
        asinList.add("B0BRCPGC7B");//Karaca Mastermaid Chef Pro Çift Kollu Mutfak Şefi 1500 W Iconic Beige
        asinList.add("B0BR3WLFVN");//Karaca Mastermaid Chef Pro Çift Kollu Mutfak Şefi 1500 W Space Gray
        asinList.add("B0C1HB8ZC8");//Karaca Mastermaid Chef Pro Çift Kollu Mutfak Şefi 1500 W Pink
        asinList.add("B0BFXL9N7N");//Karaca Mastermaid Chef Pro 1750 W Çift Kollu Stand Mikser, Shiny Black
        asinList.add("B0BFXM2DS6");//Karaca Mastermaid Chef Pro Çift Kollu Stand Mikser Kırmızı 1750 W
        asinList.add("B0C1P3SH8Z");//Karaca Mastermaid Chef Pro Çift Kollu Stand Mikser Matte Black Copper 1750 W
        asinList.add("B0C1P5JPPV");//Karaca Mastermaid Chef Pro Çift Kollu Stand Mikser 1750W Black Silver
        //Karaca Hamur Mak

        //Ramazan Listesi
        asinList.add("B0BRNF848D");
        asinList.add("B07N8N6C85");
        asinList.add("B08VJFSMGB");
        asinList.add("B08T5WSLZL");
        asinList.add("B09TBGR44Q");
        asinList.add("B0BL6NL1DD");
        asinList.add("B01J5FGWGG");
        asinList.add("B092DS3RDL");
        asinList.add("B08CBJ8W9W");
        asinList.add("B0BZ175SVS");
        asinList.add("B0BRNFKD8P");
        asinList.add("B0BLBY1YGD");
        asinList.add("B09GBFHPM2");
        asinList.add("B08BQ22GX9");
        asinList.add("B08HQQFDW4");
        asinList.add("B0BFXM2DS6");
        asinList.add("B0CRDM9HY1");
        asinList.add("B0CZ7D5DTQ");
        asinList.add("B0767DNSMH");
        asinList.add("B09M7PQ82X");
        asinList.add("B07YNZJSB9");
        asinList.add("B0CZ7BV85B");
        asinList.add("B0BWRSF3CJ");
        asinList.add("B07C43Z2GF");
        asinList.add("B0BKQQ2BPS");
        asinList.add("B09DL8DQVB");
        asinList.add("B0832WY12L");
        asinList.add("B09P3WRHF7");
        asinList.add("B07MMSHC4R");
        asinList.add("B0C53N6LG6");
        asinList.add("B0CD2KVVRC");
        asinList.add("B096MRDH6R");
        asinList.add("B08CBJVNCV");
        asinList.add("B096MRMV33");
        asinList.add("B093GLYGL8");
        asinList.add("B07QP7T8ZK");
        asinList.add("B07K56XSJ1");
        asinList.add("B09W5G56D1");
        asinList.add("B09F9XDDN2");
        asinList.add("B09VY8982D");
        asinList.add("B0936FGLQS");
        asinList.add("B09WRSTJM6");
        asinList.add("B0BZ4NZDZN");
        asinList.add("B0BXM27M5X");
        asinList.add("B07B2WQPZ7");
        asinList.add("B0B17BMM73");
        asinList.add("B0832WLDLC");
        asinList.add("B08922NLKD");
        asinList.add("B0C7RHJMF6");
        asinList.add("B0C1HB8ZC8");
        asinList.add("B09M7D4G7V");
        asinList.add("B07YNZWR56");
        asinList.add("B07BP8JRS1");
        asinList.add("B08KGDS4CZ");
        asinList.add("B0BRCPGC7B");
        asinList.add("B0BF17GJCZ");
        asinList.add("B0BS1BQ84Y");
        asinList.add("B07YNYSW5M");
        asinList.add("B09XN9K9CG");
        asinList.add("B08L7LSSR1");
        asinList.add("B0BJQK6GK4");
        asinList.add("B07M8J529S");
        asinList.add("B0864DLLP8");
        asinList.add("B09PMKYLK4");
        asinList.add("B06XCFCMJZ");
        asinList.add("B07P7PLVK3");
        asinList.add("B09FF8GFBX");
        asinList.add("B0B915YZD5");
        asinList.add("B0B88RDCSR");
        asinList.add("B0BWJW8HTL");
        asinList.add("B085Y464MR");
        asinList.add("B07QM7DF9T");
        asinList.add("B08Q8ZXKK8");
        asinList.add("B0CLNZ4NPV");
        asinList.add("B01MT60NRQ");
        asinList.add("B092DRG25L");
        asinList.add("B09HMK5XR4");
        asinList.add("B08B4WYQRD");
        asinList.add("B00FMS0BPE");
        asinList.add("B08Y9DKFVV");
        asinList.add("B09VXWR2MH");
        asinList.add("B07MMSWP78");
        asinList.add("B0BWKLDVDQ");
        asinList.add("B08DG7KPDM");
        asinList.add("B0BFB272XL");
        asinList.add("B096MRP711");
        asinList.add("B08Z4HCGDH");
        asinList.add("B088RWVDN9");
        asinList.add("B08GY2BQJC");
        asinList.add("B07BNNDH97");
        asinList.add("B0BZDX2626");
        asinList.add("B099ZT1VYR");
        asinList.add("B0C669D598");
        asinList.add("B0BG2XCPBQ");
        asinList.add("B0B7JZX2TS");
        asinList.add("B0BYZZSWY7");
        asinList.add("B092DT2DBF");
        asinList.add("B09VT6TPLS");
        asinList.add("B092D9Y4KX");
        asinList.add("B08CVWC4X5");
        asinList.add("B0B2W2XWBC");
        asinList.add("B07MWT9P6B");
        asinList.add("B08PCJ8SV3");
        asinList.add("B0C1SN3Z7R");
        asinList.add("B09Z6X261D");
        asinList.add("B0C1YPQPY8");
        asinList.add("B0BRVT1GKY");
        asinList.add("B0BFXMR7V7");
        asinList.add("B0BG5KGSYQ");
        asinList.add("B0B4WLJSV1");
        asinList.add("B09VT7NR7Z");
        asinList.add("B09HMGQHDB");
        asinList.add("B0BJNW9H1K");
        asinList.add("B0B5DYYNYZ");
        asinList.add("B07X1BLGC7");
        asinList.add("B07CVTPD9Y");
        asinList.add("B09M8VX6S3");
        asinList.add("B09SP4FJ6H");
        asinList.add("B08WNCGR84");
        asinList.add("B0C8VF2HXB");
        asinList.add("B0764KRMY3");
        asinList.add("B08S787DSS");
        asinList.add("B0C24CH4WM");
        asinList.add("B0BFBFJDR1");
        asinList.add("B0B6GP29NK");
        asinList.add("B0BNNC3767");
        asinList.add("B00E38652C");
        asinList.add("B079BMMNP7");
        asinList.add("B0933CBLSM");
        asinList.add("B09132G56D");
        asinList.add("B08GGMQS8W");
        asinList.add("B01HJUONBU");
        asinList.add("B07M8J529L");
        asinList.add("B0BQCH5X9J");
        asinList.add("B0BZJJJPMJ");
        asinList.add("B0CKWFLCL5");
        asinList.add("B08BFGQYZ3");
        asinList.add("B09BVH86BR");
        asinList.add("B0B1HN2JQ8");
        asinList.add("B00R04CAWA");
        asinList.add("B0B1JPZDNW");
        asinList.add("B07KSCV37M");
        asinList.add("B0BS48HQ3Z");
        asinList.add("B0BQCJRQ5L");
        asinList.add("B00G59DYI0");
        asinList.add("B078HFLPW7");
        asinList.add("B0CSKBHS9J");
        asinList.add("B07NLRC4NR");
        asinList.add("B0BJQP23Y8");
        asinList.add("B092JS22CV");
        asinList.add("B0C2W2HYN9");
        asinList.add("B0B18X334Q");
        asinList.add("B09VXWLLQK");
        asinList.add("B0CNW73SGV");
        asinList.add("B0CKWFQJXR");
        asinList.add("B00NXVEL5I");
        asinList.add("B09K4BKQ4X");
        asinList.add("B085V2JYFS");
        asinList.add("B09339X6TW");
        asinList.add("B0BWVK9P5L");
        asinList.add("B08443FKT8");
        asinList.add("B07GG96ZGG");
        asinList.add("B09VZP1J94");
        asinList.add("B09BNM8FFX");
        asinList.add("B07L6X4K3T");
        asinList.add("B075FC8ZJ3");
        asinList.add("B0979HTPDQ");
        asinList.add("B0C7VFD9Q4");
        asinList.add("B0C14F6C96");
        asinList.add("B09DLBDHKH");
        asinList.add("B0B829K872");
        asinList.add("B099KS4CPM");
        asinList.add("B09CYYNTKK");
        asinList.add("B0BH1C6KZL");
        asinList.add("B08TCG4DR4");
        asinList.add("B0B294N691");
        asinList.add("B0BQWSP781");
        asinList.add("B00KA5SULQ");
        asinList.add("B0BGGJH3G2");
        asinList.add("B09WYWPY14");
        asinList.add("B082VD839K");
        asinList.add("B00U65CWFA");
        asinList.add("B0CH654LZ7");
        asinList.add("B07HZGXSLT");
        asinList.add("B09HQXK9Y6");
        asinList.add("B0CN6RX6X8");
        asinList.add("B078XFQX5J");
        asinList.add("B07CT3JLBH");
        asinList.add("B09M8XGS92");
        asinList.add("B0CXQ4DLZY");
        asinList.add("B0C7RGNNW2");
        asinList.add("B07B4LSCZ4");
        asinList.add("B08KJDHJCB");
        asinList.add("B087NXXP9X");
        asinList.add("B0CZ7CBT9M");
        asinList.add("B0CJWY1B7G");
        asinList.add("B0BWKCDFQJ");
        asinList.add("B0C33N83DB");
        asinList.add("B08SBGBW9X");
        asinList.add("B0BF53SSDM");
        asinList.add("B0C4L8D11B");
        asinList.add("B0BF151LNW");
        asinList.add("B0969X98ZN");
        asinList.add("B0C46STQ74");
        asinList.add("B01N9XBDTI");
        asinList.add("B0BR3WLFVN");
        asinList.add("B075P14QGX");
        asinList.add("B077ZCT9WW");
        asinList.add("B07G8DF8T6");
        asinList.add("B09CD8RF2X");
        asinList.add("B0C2Q8S6PG");
        asinList.add("B012FA8JLY");
        asinList.add("B077ZJXCY1");
        asinList.add("B09LD1QF1P");
        asinList.add("B087XKC42F");
        asinList.add("B0B25TNXJS");
        asinList.add("B092W23P5T");
        asinList.add("B09H2S75KT");
        asinList.add("B082TPKS1D");
        asinList.add("B09S1JC2RW");
        asinList.add("B07TWRKXCF");
        asinList.add("B082YL9NFN");
        asinList.add("B0CZ7P3DL4");
        asinList.add("B00NXVENAQ");
        asinList.add("B084CXDZHJ");
        asinList.add("B0C1P5JPPV");
        asinList.add("B0C2QJB7MX");
        asinList.add("B0BDZC351S");
        asinList.add("B0BQR5J7JT");
        asinList.add("B09GBBMGQT");
        asinList.add("B0BG2LC8Y7");
        asinList.add("B0BF195GYK");
        asinList.add("B0BJYYJFLJ");
        asinList.add("B08R24FVGL");
        asinList.add("B07NSDWBMX");
        asinList.add("B0C2W2H4XR");
        asinList.add("B09VXSY3GT");
        asinList.add("B0CTH8LXQN");
        asinList.add("B0BMVCVC85");
        asinList.add("B0C6687RSC");
        asinList.add("B07SPGNK29");
        asinList.add("B07F2RGGFF");
        asinList.add("B0BWS5SZSY");
        asinList.add("B01NAWFDLU");
        asinList.add("B0CP5Y391N");
        asinList.add("B07DF2CS32");
        asinList.add("B01HQ12WJC");
        asinList.add("B07B4T8QWN");
        asinList.add("B0BWS7N56L");
        asinList.add("B07YNZ6HPV");
        asinList.add("B0BR9W7XBB");
        asinList.add("B0CJC3VTH5");
        asinList.add("B0978YBC3V");
        asinList.add("B0799FBJS9");
        asinList.add("B0B41N8S81");
        asinList.add("B0BW4FDZXY");
        asinList.add("B0979K4RQN");
        asinList.add("B077ZJC1RB");
        asinList.add("B0CHYBJMCR");
        asinList.add("B0CC2FBJZR");
        asinList.add("B0BG5G8QFN");
        asinList.add("B085N8BJM5");
        asinList.add("B08SBXQ8VJ");
        asinList.add("B08TWPG5LK");
        asinList.add("B01N8YAKO0");
        asinList.add("B0CGF9J3D9");
        asinList.add("B07998PKM6");
        asinList.add("B08BC9ZRNR");
        asinList.add("B07C44LNYS");
        asinList.add("B0BC9V84LJ");
        asinList.add("B0BMQRRJQP");
        asinList.add("B07CJK139P");
        asinList.add("B084PSXMQM");
        asinList.add("B092LWNLZ6");
        asinList.add("B0C3WKM8QN");
        asinList.add("B0C74DJ6ZS");
        asinList.add("B0BXM27JKX");
        asinList.add("B0C66G6W6V");
        asinList.add("B00SS1OSDI");
        asinList.add("B08MXMWSFY");
        asinList.add("B0B136KCXP");
        asinList.add("B07YP3T2JH");
        asinList.add("B0CGXC8QG5");
        asinList.add("B088S336ZZ");
        asinList.add("B09VGM3XG1");
        asinList.add("B0867CCLZ9");
        asinList.add("B00IOKXHQC");
        asinList.add("B0CBD8RN23");
        asinList.add("B08TWQ491M");
        asinList.add("B09VLJ2PPR");
        asinList.add("B01M18E66E");
        asinList.add("B0BC9WZFWF");
        asinList.add("B0C33R5Y7P");
        asinList.add("B0B4ZTBHPN");
        asinList.add("B09QSVG2QS");
        asinList.add("B0C74G9QM3");
        asinList.add("B0845P3ZRP");
        asinList.add("B0C4YRMC9Y");
        asinList.add("B07H1WHH37");
        asinList.add("B08TKTGQX1");
        asinList.add("B01MZ74PGL");
        asinList.add("B0BKQRWL1H");
        asinList.add("B0CGF9B2JT");
        asinList.add("B0C6W8BHMF");
        asinList.add("B0937BN25N");
        asinList.add("B087D1ZJ4S");
        asinList.add("B07YNJT5N5");
        asinList.add("B086D7SBRY");
        asinList.add("B0BQCFF4GM");
        asinList.add("B07L6X2QYG");
        asinList.add("B0844LSWD3");
        asinList.add("B0BBBNYTY6");
        asinList.add("B00R04CAH0");
        asinList.add("B0C1P59N7Y");
        asinList.add("B07P6KJC5C");
        asinList.add("B07KYD46QR");
        asinList.add("B07999PQG1");
        asinList.add("B08KTCQQNX");
        asinList.add("B0CBSHHJS6");
        asinList.add("B015FO9XF8");
        asinList.add("B0857W3V1X");
        asinList.add("B07PHH6SP7");
        asinList.add("B0B4P9VJLK");
        asinList.add("B09SYD2BDW");
        asinList.add("B086HZWBLP");
        asinList.add("B09TV6FM8M");
        asinList.add("B09DCNF81X");
        asinList.add("B09PY6SLWV");
        asinList.add("B0B5D7H7VP");
        asinList.add("B08C7WR5PB");
        asinList.add("B07YYJCP9Z");
        asinList.add("B08DTJB2D5");
        asinList.add("B0BRVSJ7SS");
        asinList.add("B008MZKS5C");
        asinList.add("B089NYBMK2");
        asinList.add("B08TL4119V");
        asinList.add("B08WJ8SDVZ");
        asinList.add("B002007HQI");
        asinList.add("B07B4LX33J");
        asinList.add("B08P7WBBXP");
        asinList.add("B0CH64G76F");
        asinList.add("B09448T4BK");
        asinList.add("B079997V1L");
        asinList.add("B0B18W5PQK");
        asinList.add("B07BPBR89Y");
        asinList.add("B071VCXRFQ");
        asinList.add("B0BC9P5612");
        asinList.add("B0B8DS337Z");
        asinList.add("B0D7M5G3ZK");
        asinList.add("B08GX4SL9F");
        asinList.add("B09M7KR1VW");
        asinList.add("B0CC8Y3XBB");
        asinList.add("B07997SH4P");
        asinList.add("B019381OMC");
        asinList.add("B0BFRP6MD5");
        asinList.add("B0C4FMNXTH");
        asinList.add("B09PL852BW");
        asinList.add("B09GB98SXH");
        asinList.add("B0CKWD9J3R");
        asinList.add("B0BRD9B86W");
        asinList.add("B075F78KDV");
        asinList.add("B08SBYSK49");
        asinList.add("B08GDBYCG6");
        asinList.add("B09TV3PVQ2");
        asinList.add("B0D7M9GW7P");
        asinList.add("B0C5JRF3CP");
        asinList.add("B0BX9FSZ7T");
        asinList.add("B07K5765KL");
        asinList.add("B07L6P25GY");
        asinList.add("B08CZT7GTD");
        asinList.add("B09QX6JN98");
        asinList.add("B07C85ZGLS");
        asinList.add("B076CKRKMB");
        asinList.add("B0BZJJZ9HP");
        asinList.add("B0CGF9F76W");
        asinList.add("B07998XRDP");
        asinList.add("B092DQKKMS");
        asinList.add("B07G94NPKJ");
        asinList.add("B08D6CR4N9");
        asinList.add("B09GSYWRDK");
        asinList.add("B074M9DZ4M");
        asinList.add("B078478VVF");
        asinList.add("B0C1P3SH8Z");
        asinList.add("B0B42ZB9TV");
        asinList.add("B0BQCFXNTK");
        asinList.add("B0764FSTYR");
        asinList.add("B086RF6YJQ");
        asinList.add("B00QKBVML4");
        asinList.add("B0CJQXKMJ7");
        asinList.add("B087G645T8");
        asinList.add("B09VT793T6");
        asinList.add("B084DPS234");
        asinList.add("B0799CLLHX");
        asinList.add("B0B4W1F92G");
        asinList.add("B0C978VRTZ");
        asinList.add("B07CPZWMC4");
        asinList.add("B08GDDGSKS");
        asinList.add("B07ML49BPN");
        asinList.add("B08T5WWVZJ");
        asinList.add("B018O4RKYC");
        asinList.add("B07MJ3V81F");
        asinList.add("B07CL759N4");
        asinList.add("B084W1FZJ8");
        asinList.add("B00FGR1CJA");
        asinList.add("B0BRVTFHQD");
        asinList.add("B0C2J7Q91Q");
        asinList.add("B01N0Y6D8Z");
        asinList.add("B09GRFVD1P");
        asinList.add("B0BC9YM9QC");
        asinList.add("B0BLBTRXJM");
        asinList.add("B0BS1Q7644");
        asinList.add("B07VVK39F7");
        asinList.add("B0CHF3J8GN");
        asinList.add("B089T486LG");
        asinList.add("B08T1LRSCL");
        asinList.add("B09TR7QD2S");
        asinList.add("B07DX2MV3X");
        asinList.add("B0BZ16HDK9");
        asinList.add("B0CH6N3CCB");
        asinList.add("B08P5NNNL5");
        asinList.add("B07C33HWNJ");
        asinList.add("B0C58N5YBJ");
        asinList.add("B0BF4WG3YW");
        asinList.add("B091Z6SH7W");
        asinList.add("B01N1M3ZNK");
        asinList.add("B09X4VFHBX");
        asinList.add("B0D4ZMQLNH");
        asinList.add("B07NVBHPG7");
        asinList.add("B08TV4124X");
        asinList.add("B07BM6XZYF");
        asinList.add("B001I902LO");
        asinList.add("B08447L6Y2");
        asinList.add("B07BNVMBM7");
        asinList.add("B07G7TFDQ4");
        asinList.add("B0BTQX7KSG");
        asinList.add("B09VT85T8H");
        asinList.add("B01BWMABX0");
        asinList.add("B07C41BYQR");
        asinList.add("B01I99P1FM");
        asinList.add("B087V5M16F");
        asinList.add("B09KB9MBHB");
        asinList.add("B08VNH1R56");
        asinList.add("B0CFYMYC97");
        asinList.add("B012Z7VO5A");
        asinList.add("B0C1P6YH3V");
        asinList.add("B07BSH39F8");
        asinList.add("B08WRBGX2T");
        asinList.add("B0D7M7Q6LW");
        asinList.add("B0BWS7TP4P");
        asinList.add("B0B62L9R7C");
        asinList.add("B0CQCL1NYK");
        asinList.add("B0CPM7DYT2");
        asinList.add("B08GDBDM6R");
        asinList.add("B08GDC4N5V");
        asinList.add("B006TF4S3U");
        asinList.add("B09P6FHT99");
        asinList.add("B09GP7FRMJ");
        asinList.add("B00A3BPC4K");
        asinList.add("B0BWJM5CV9");
        asinList.add("B0C72P8JG8");
        asinList.add("B0C4DVXF42");
        asinList.add("B0CN8TQ87K");
        asinList.add("B09SHN8F2Y");
        asinList.add("B06ZZX5FHW");
        asinList.add("B092MCYWQY");
        asinList.add("B08KJFJKC9");
        asinList.add("B07BQC57M7");
        asinList.add("B0C28GNRR7");
        asinList.add("B09TRB5GMD");
        asinList.add("B09TLBRCR3");
        asinList.add("B0BSNCXJ6R");
        asinList.add("B084ZJTYTS");
        asinList.add("B09NMHJRCL");
        asinList.add("B003H0TZ2E");
        asinList.add("B0BQ2RV7ZQ");
        asinList.add("B083P74CD4");
        asinList.add("B000TGII5Y");
        asinList.add("B09WQK1SMH");
        asinList.add("B07R7QYC65");
        asinList.add("B005Z0OEBQ");
        asinList.add("B0BFR4R7W7");
        asinList.add("B09963Q18P");
        asinList.add("B07YN8TNTQ");
        asinList.add("B086VVWJ6K");
        asinList.add("B08HZ8J8M8");
        asinList.add("B07BMJBB5H");
        asinList.add("B08TSF3MRG");
        asinList.add("B01IHDWVL2");
        asinList.add("B07D8WLV7S");
        asinList.add("B07BNRR3LW");
        asinList.add("B012FZBY2A");
        asinList.add("B07CPSCKTJ");
        asinList.add("B0BQ2V7M2X");
        asinList.add("B087KRNLPR");
        asinList.add("B074KQXMSJ");
        asinList.add("B07F38RDRM");
        asinList.add("B0CZTT41SV");
        asinList.add("B0BBLLNDW5");
        asinList.add("B07C36WQ7V");
        asinList.add("B0B3JKP2VW");
        asinList.add("B0C6FGGK7F");
        asinList.add("B0C8NVFGX7");
        asinList.add("B0BRYBK2PR");
        asinList.add("B0C85JQYQ6");
        asinList.add("B0CJYF4XT8");
        asinList.add("B0BYJWZKYH");
        asinList.add("B0CCNW5CC9");
        asinList.add("B0CJYFF9XY");
        asinList.add("B0CJYC9ZC1");
        asinList.add("B0CCPJQZNG");
        asinList.add("B0C85RJPZT");
        asinList.add("B0C85VDMDX");
        asinList.add("B0B5R992W6");
        asinList.add("B0CD9FBL6R");
        asinList.add("B0C85HX5GW");
        asinList.add("B0CGDC4CVS");
        asinList.add("B0CGD9RM3L");
        asinList.add("B0CLP8D7GN");
        asinList.add("B0BTDP58QZ");
        asinList.add("B0C6FLP473");
        asinList.add("B0C85K2TP8");
        asinList.add("B0C1K8T32W");
        asinList.add("B0CLP7HLRL");
        asinList.add("B0CJYC7FHH");
        asinList.add("B0CJYCLXSH");
        asinList.add("B0CKVJ5R3J");
        asinList.add("B0C85JJ8VG");
        asinList.add("B0CJWC9H57");
        asinList.add("B0BVPBFFKH");
        asinList.add("B0C6FLP5FD");
        asinList.add("B07NZZZ746");
        asinList.add("B0C81XCRPR");
        asinList.add("B0BX4G1LHQ");
        asinList.add("B0CH9WGNFG");
        asinList.add("B0CQ9QT5PL");
        asinList.add("B0C762M6JW");
        asinList.add("B0CQRMPQCP");
        asinList.add("B0CCNT1YKF");
        asinList.add("B09V4B6G7H");
        asinList.add("B08NGQDBWX");
        asinList.add("B07QHQ4P5H");
        asinList.add("B0CF65G3NQ");
        asinList.add("B0CPSB82GZ");
        asinList.add("B08HQW9SGP");
        asinList.add("B0CM5T5QPV");
        asinList.add("B0CK84W742");
        asinList.add("B0B6ZZDLXC");
        asinList.add("B0C7LS1RKS");
        asinList.add("B09Y55J2M3");
        asinList.add("B0CH9W84RV");
        asinList.add("B0BH4JXLMX");
        asinList.add("B0BTDMZ52C");
        asinList.add("B0BTKJHWYF");
        asinList.add("B0CJW5TNSM");
        asinList.add("B0C81JBP66");
        asinList.add("B08QJHLC8J");
        asinList.add("B0CD984MJB");
        asinList.add("B0BMM57P3B");
        asinList.add("B0BJM6PXXM");
        asinList.add("B0CJW8MVZD");
        asinList.add("B0BJM6WSVV");
        asinList.add("B0BNGNMY3G");
        asinList.add("B00SAYCVTQ");
        asinList.add("B0CBHTHDXR");
        asinList.add("B09QD1TTXP");
        asinList.add("B0C9DLN854");
        asinList.add("B0CJFYLQYW");
        asinList.add("B0BY32GGPN");
        asinList.add("B0CJFW6PR7");
        asinList.add("B0BDXTQYSH");
        asinList.add("B09V4NW4VM");
        asinList.add("B07W6JNG13");
        asinList.add("B09NC3MQ9L");
        asinList.add("B0C7W28Y14");
        asinList.add("B0CLP636Z3");
        asinList.add("B0BJN312BH");
        asinList.add("B0BL8G6K6R");
        asinList.add("B0CH5RHTYH");
        asinList.add("B0CBKTFB1J");
        asinList.add("B0C75ZSSMM");
        asinList.add("B0CCPFNK81");
        asinList.add("B0CJVTJSY2");
        asinList.add("B0BJMKXN9M");
        asinList.add("B0CLNQVVNZ");
        asinList.add("B0BSGYSK88");
        asinList.add("B0CD988CG2");
        asinList.add("B0CK871H2F");
        asinList.add("B0CQTKT992");
        asinList.add("B0B3C556JD");
        asinList.add("B0CB8H2L27");
        asinList.add("B0CQ9VSS76");
        asinList.add("B0CCQKTLFH");
        asinList.add("B0CJG1D1MX");
        asinList.add("B0CJFY98BX");
        asinList.add("B0BWHPK6VB");
        asinList.add("B097TM6MRZ");
        asinList.add("B0B3C2YVFT");
        asinList.add("B0CVHBV32W");
        asinList.add("B0BJL7TFD6");
        asinList.add("B0B8N26Z78");
        asinList.add("B0CSDQMJGT");
        asinList.add("B0B3CPLWVT");
        asinList.add("B0CL78586V");
        asinList.add("B0CQTLTMH7");
        asinList.add("B0CNKCQNNL");
        asinList.add("B08F7NWJY5");
        asinList.add("B0B3C92RXD");
        asinList.add("B0CGQ41W6V");
        asinList.add("B0C6FGGH9Q");
        asinList.add("B0CPJ6W7ZS");
        asinList.add("B0C85X799P");
        asinList.add("B0CHT6G3V6");
        asinList.add("B09GW4KWKM");
        asinList.add("B086XXYQMV");
        asinList.add("B0C6FJ34NT");
        asinList.add("B0BYZ6XT13");
        asinList.add("B09V5JQG17");
        asinList.add("B0CK84JN45");
        asinList.add("B0BQMNKT86");
        asinList.add("B0C2R98VXN");
        asinList.add("B0BYJXMX25");
        asinList.add("B09G9ST1VQ");
        asinList.add("B0CNKC6H7J");
        asinList.add("B0BZCRRYYR");
        asinList.add("B09BCDQK63");
        asinList.add("B09VH2X4ZZ");
        asinList.add("B07W4DJRC5");
        asinList.add("B08JD4TBM3");
        asinList.add("B0CCPFBQX5");
        asinList.add("B08NX6KLX2");
        asinList.add("B0C85J8QP9");
        asinList.add("B0CSKJY3GM");
        asinList.add("B0CQTKLH1R");
        asinList.add("B0BZMLDGFK");
        asinList.add("B0BQCC78ZK");
        asinList.add("B0CJWGMKCQ");
        asinList.add("B08NGQSWYK");
        asinList.add("B0BJMYCT6Y");
        asinList.add("B0C5HNRD4M");
        asinList.add("B0CQ9QSG54");
        asinList.add("B0CJVVB68N");
        asinList.add("B09QV692XY");
        asinList.add("B09XDH2P6P");
        asinList.add("B0B1BCTPMY");
        asinList.add("B0CJWSKGS4");
        asinList.add("B0CZ3LWDVR");
        asinList.add("B0C6FJNSYP");
        asinList.add("B08NGRKQ7K");
        asinList.add("B0BH4ZY4SH");
        asinList.add("B0B6JLST8M");
        asinList.add("B09SKZV1WZ");
        asinList.add("B08HN37XC1");
        asinList.add("B0CCNPLR9T");
        asinList.add("B0983FZVKZ");
        asinList.add("B06XGHTP9Z");
        asinList.add("B08BHW7GBL");
        asinList.add("B0BKNZSBRY");
        asinList.add("B0CQRKSDYC");
        asinList.add("B08V85DH1R");
        asinList.add("B0BBWH1R8H");
        asinList.add("B07D94LMHV");
        asinList.add("B082NRKT4K");
        asinList.add("B0CCNV8XBW");
        asinList.add("B0CYM6HF33");
        asinList.add("B0C6YCTDHF");
        asinList.add("B09G9RXGDT");
        asinList.add("B0CSKJ33Q7");
        asinList.add("B09WRCW3JX");
        asinList.add("B01N0AJVB1");
        asinList.add("B0CLRTG5NQ");
        asinList.add("B08GS7748F");
        asinList.add("B09K7F5VJQ");
        asinList.add("B0BRL8QVFB");
        asinList.add("B01A9GXEOI");
        asinList.add("B0C245NVH2");
        asinList.add("B07Y3PMCGY");
        asinList.add("B0CBHTNFVG");
        asinList.add("B007795T3A");
        asinList.add("B09Y9FKBFX");
        asinList.add("B0BR5S3NQM");
        asinList.add("B0BJMPTXCP");
        asinList.add("B0BM42X58C");
        asinList.add("B0BJMKTF9R");
        asinList.add("B0BYBFLK3Y");
        asinList.add("B09V4ZT8SX");
        asinList.add("B0C4TW12WT");
        asinList.add("B0CP4CWRLX");
        asinList.add("B0C81DRHL2");
        asinList.add("B0BTZB7F88");
        asinList.add("B08JD5PV9F");
        asinList.add("B0BTLSBF6M");
        asinList.add("B07VMTNDMK");
        asinList.add("B0CQTKWH2M");
        asinList.add("B0BJM1Q1WQ");
        asinList.add("B09G9PPFWX");
        asinList.add("B0BS6V4BTF");
        asinList.add("B07QKC4WWD");
        asinList.add("B01MXJVMGX");
        asinList.add("B09VH2F1J5");
        asinList.add("B0C4F7KX1B");
        asinList.add("B08NVSJ96M");
        asinList.add("B08PPYCQM9");
        asinList.add("B0BZ57Q7DF");
        asinList.add("B09G9PRLM4");
        asinList.add("B08PQ1278V");
        asinList.add("B08PQ1JPX9");
        asinList.add("B0BSLXCGKB");
        asinList.add("B0BXYBHYXQ");
        asinList.add("B0C4PZRXMK");
        asinList.add("B0BZ59PHL1");
        asinList.add("B08PQ2BKDD");
        asinList.add("B0C4VJ397B");
        asinList.add("B09BJHYX7N");
        asinList.add("B0CL7TV449");
        asinList.add("B0BKQLZNH6");
        asinList.add("B0CL74T8F5");
        asinList.add("B0C28JDKRZ");
        asinList.add("B09G9PNHLQ");
        asinList.add("B0BZ5HWQ1N");
        asinList.add("B0BZ5HWQ1R");
        asinList.add("B09WF22W2F");
        asinList.add("B0CR6R9BTG");
        asinList.add("B09V4DXDT9");
        asinList.add("B09G9RBDBZ");
        asinList.add("B0BDJP22LN");
        asinList.add("B0C28KMJMM");
        asinList.add("B0BZ58RQTK");
        asinList.add("B0CHXRKZJ9");
        asinList.add("B0C2PXKQ3B");
        asinList.add("B09G9QMZMP");
        asinList.add("B08QZ3WJMH");
        asinList.add("B09ZSPH2TY");
        asinList.add("B0CHWZ8Y8H");
        asinList.add("B0BM4QGVTC");
        asinList.add("B0C2PVSFD1");
        asinList.add("B0CR6RCV1Q");
        asinList.add("B0CHX46FX6");
        asinList.add("B0BDJDDZZV");
        asinList.add("B0BQ6WKS8V");
        asinList.add("B09G9RQTP3");
        asinList.add("B0BXYN95F9");
        asinList.add("B0CHX5TWQM");
        asinList.add("B0BQ6WJCP3");
        asinList.add("B0CR6RJ24F");
        asinList.add("B0CR6R99BG");
        asinList.add("B0CM25Y89L");
        asinList.add("B09WDY964R");
        asinList.add("B0CHXMLVKJ");
        asinList.add("B09HXL49HM");
        asinList.add("B0CHX43FKD");
        asinList.add("B0CR6R5M9S");
        asinList.add("B0BXY3XFRV");
        asinList.add("B0C28GH8R6");
        asinList.add("B0BDJ53N2Q");
        asinList.add("B0BSLY99Q9");
        asinList.add("B0CHX9577V");
        asinList.add("B0CHXDQMQK");
        asinList.add("B09G9SV81G");
        asinList.add("B09TPSXTLG");
        asinList.add("B0CHXNZ6JP");
        asinList.add("B09RQVZVHQ");
        asinList.add("B0BDJB9HRQ");
        asinList.add("B0BDJFT3TW");
        asinList.add("B0CHX9JCVV");
        asinList.add("B0BZ5N4555");
        asinList.add("B09V4V3BNV");
        asinList.add("B0BZ5C9199");
        asinList.add("B09V4BQG8X");
        asinList.add("B0BKQNQ8WZ");
        asinList.add("B0CHX78Q74");
        asinList.add("B0CR6RN4HP");
        asinList.add("B0CHX4LMJ5");
        asinList.add("B0CYH527VN");
        asinList.add("B0CYH3JCRS");
        asinList.add("B0B9P2M5K3");
        asinList.add("B095WCJBRK");
        asinList.add("B0C28MMWWW");
        asinList.add("B0CM2621GM");
        asinList.add("B0CHXK971Y");
        asinList.add("B0CQKCQ8PH");
        asinList.add("B0CPXZ9F5V");
        asinList.add("B09ZXBZRFW");
        asinList.add("B0BDJ4M383");
        asinList.add("B0BDJMRLMS");
        asinList.add("B0C4PXTXYT");
        asinList.add("B0C2PWBBLZ");
        asinList.add("B0CPFR1XZ9");
        asinList.add("B0CR6S1QQZ");
        asinList.add("B0CR6S7BRM");
        asinList.add("B0CPXX34K2");
        asinList.add("B0CR6T8WT5");
        asinList.add("B0BSLXSZ8Y");
        asinList.add("B0CHXC99XN");
        asinList.add("B0CBZ8V625");
        asinList.add("B0BDJ2RNKR");
        asinList.add("B08NVTT7ZV");
        asinList.add("B0CHXRNHC4");
        asinList.add("B08NVS66NB");
        asinList.add("B0BDJ5C5QY");
        asinList.add("B0BSLWP2DM");
        asinList.add("B08NVRQJLN");
        asinList.add("B0C28HT7XS");
        asinList.add("B0CHXGB3NG");
        asinList.add("B0CHXCFS1J");
        asinList.add("B09BFQX7RP");
        asinList.add("B00E0GHXOG");
        asinList.add("B0BDJ2YQFN");
        asinList.add("B0BDJFLDXC");
        asinList.add("B09TPRDDGQ");
        asinList.add("B0C28HH5TK");
        asinList.add("B0BSLW3NNN");
        asinList.add("B0BDJ7LSTT");
        asinList.add("B0CJ35K5MN");
        asinList.add("B09ZXS5TYN");
        asinList.add("B0CKY22Y7T");
        asinList.add("B0CFP8QTXY");
        asinList.add("B09RQWSBJJ");
        asinList.add("B0BDHTPJ8G");
        asinList.add("B09ZXYQTFQ");
        asinList.add("B09RQWJVH2");
        asinList.add("B0CR6QT9WZ");
        asinList.add("B09G9RK6XN");
        asinList.add("B0CHXGPMK5");
        asinList.add("B0CWP8PCD5");
        asinList.add("B0BM4SP5PX");
        asinList.add("B09G9PS7D2");
        asinList.add("B09G9RGQ6T");
        asinList.add("B09G9RPNMY");
        asinList.add("B0BKQKQ5JT");
        asinList.add("B0CR6QYDWZ");
        asinList.add("B0CR6SMJNR");
        asinList.add("B0CJ364JR6");
        asinList.add("B0BDJFZBFD");
        asinList.add("B09JZTFQ58");
        asinList.add("B08NTSMQYC");
        asinList.add("B08NVSFBKB");
        asinList.add("B09BJGFW89");
        asinList.add("B0BSLWPLQW");
        asinList.add("B0BDJGPDM4");
        asinList.add("B08NVSFS4J");
        asinList.add("B0C5J4M8HD");
        asinList.add("B08NVSPSX4");
        asinList.add("B0CCL2N7GV");
        asinList.add("B00MN26FFC");
        asinList.add("B0972ZJJW8");
        asinList.add("B0BZ5SG9X7");
        asinList.add("B08NVP5B1T");
        asinList.add("B0D383ZXKK");
        asinList.add("B0CPXYTPYC");
        asinList.add("B0CFPNDZWV");
        asinList.add("B0CR6RN4HQ");
        asinList.add("B0CHX1JRJ4");
        asinList.add("B0BDVWRXMH");
        asinList.add("B0CFPQVNVC");
        asinList.add("B09SZ6RDKH");
        asinList.add("B082HQ6M7R");
        asinList.add("B093QDK9B8");
        asinList.add("B0BJF68C2H");
        asinList.add("B09HXM65M8");
        asinList.add("B0BDJCK7CH");
        asinList.add("B0BDJS2919");
        asinList.add("B0CM26Q46M");
        asinList.add("B092TN8FWV");
        asinList.add("B0CBHTQNHB");
        asinList.add("B0886C3SR8");
        asinList.add("B0CYH5MHT2");
        asinList.add("B0CHX1DS99");
        asinList.add("B0CJ342WM3");
        asinList.add("B0BZVMBM3V");
        asinList.add("B0CCKZ3X53");
        asinList.add("B09ZXHHHMD");
        asinList.add("B092VV7MMJ");
        asinList.add("B09NTPTKRV");
        asinList.add("B0CHX7R91W");
        asinList.add("B0BDVTTRN6");
        asinList.add("B0CHXDJ3DK");
        asinList.add("B0BDK64HYD");
        asinList.add("B0D4R3DVHJ");
        asinList.add("B0CHX5XFQB");
        asinList.add("B0BDK9FG1Y");
        asinList.add("B0BQ6WQYG3");
        asinList.add("B00MFDJSUI");
        asinList.add("B08DCP8ZCM");
        asinList.add("B0CV5V2LCB");
        asinList.add("B09JR5M5LV");
        asinList.add("B07V7YHXY6");
        asinList.add("B0987Z64PC");
        asinList.add("B0CFPK9TJJ");
        asinList.add("B0C7ZJF5JC");
        asinList.add("B09WHVSWJ2");
        asinList.add("B0C7ZQ8TGD");
        asinList.add("B09KYMHD39");
        asinList.add("B09L1DTP51");
        asinList.add("B0BRQPLLFP");
        asinList.add("B0CFPN2L9T");
        asinList.add("B09T3CKHH9");
        asinList.add("B0CCV6QQJZ");
        asinList.add("B09TPRBMQW");
        asinList.add("B0CV3Q2918");
        asinList.add("B09K6DLRCL");
        asinList.add("B07ZZKZSTZ");
        asinList.add("B08G97TPH8");
        asinList.add("B0CBHTSS46");
        asinList.add("B0C7ZQQQ2Q");
        asinList.add("B0CR6QSK4H");
        asinList.add("B09NTNTVRJ");
        asinList.add("B0BQLGTCG3");
        asinList.add("B00BXFD3PU");
        asinList.add("B0BDJSRQCZ");
        asinList.add("B0CHXMK1MC");
        asinList.add("B0CJ34Q9WW");
        asinList.add("B0D2RKMNB7");
        asinList.add("B09ZXV7LCD");
        asinList.add("B09ZY1H1KM");
        asinList.add("B0BKSSJ7VX");
        asinList.add("B09F9Y4X3L");
        asinList.add("B0CHX5JHF1");
        asinList.add("B0B1DMRMHK");
        asinList.add("B0CR6RMCF7");
        asinList.add("B0CJ351WB8");
        asinList.add("B0B15B698H");
        asinList.add("B0BCT5QRFD");
        asinList.add("B0CYC6LHP2");
        asinList.add("B0CYC72YW2");
        asinList.add("B09V5792GL");
        asinList.add("B0B7XCG225");
        asinList.add("B0C1P4S6R6");
        asinList.add("B0CR6PRJHG");
        asinList.add("B0CR6QVPVS");
        asinList.add("B0CR6QWN9V");
        asinList.add("B0C9QT84J5");
        asinList.add("B0CBHT649L");
        asinList.add("B0CBHVW4NT");
        asinList.add("B00LEAU5KK");
        asinList.add("B09ZSPJLNS");
        asinList.add("B0CBHTP1NY");
        asinList.add("B0BS8PDB1C");
        asinList.add("B099DVTZR1");
        asinList.add("B0C93MQMRB");
        asinList.add("B0B34SM6X8");
        asinList.add("B08HH2M13H");
        asinList.add("B09T3BS29V");
        asinList.add("B0CBHV7FM1");
        asinList.add("B0BXPZRNJS");
        asinList.add("B0CBHTYVRP");
        asinList.add("B0BBR91FTX");
        asinList.add("B0BVFT9WRH");
        asinList.add("B09Y5HYN7J");
        asinList.add("B09XF99G84");
        asinList.add("B0CP1TGPKG");
        asinList.add("B09V57Q78T");
        asinList.add("B0C9QT2J6W");
        asinList.add("B01LYUKOVZ");
        asinList.add("B081FWVSG8");
        asinList.add("B091BRJSRN");
        asinList.add("B09YYQJSVJ");
        asinList.add("B0CBZ7Y47N");
        asinList.add("B09GVDBP58");
        asinList.add("B0BVFQ8WTR");
        asinList.add("B09LHND6BQ");
        asinList.add("B0C4FFTQPV");
        asinList.add("B0C4Y3TH7W");
        asinList.add("B0CCVG8LWJ");
        asinList.add("B09BFS22RD");
        asinList.add("B0BVFQP1J6");
        asinList.add("B01HH52Q5W");
        asinList.add("B09FPT7QDL");
        asinList.add("B09N4YSZSY");
        asinList.add("B09PFNP7WY");
        asinList.add("B0CK76F1X9");
        asinList.add("B09PH8BW41");
        asinList.add("B0CCVK6JGZ");
        asinList.add("B0BS8F8FTM");
        asinList.add("B0988271QZ");
        asinList.add("B07Z3VQFK3");
        asinList.add("B00MFDJNVW");
        asinList.add("B09WW1KH4J");
        asinList.add("B0144AE0V6");
        asinList.add("B0CCS3CYQC");
        asinList.add("B0B11PLHLZ");
        asinList.add("B0BVFR1HSZ");
        asinList.add("B0B5F5RQYF");
        asinList.add("B09PRD4F97");
        asinList.add("B0B46N4SK5");
        asinList.add("B09S8RCGSC");
        asinList.add("B09L4GQGYS");
        asinList.add("B0CJWBKSMS");
        asinList.add("B0B46PK8LD");
        asinList.add("B087KR6XHM");
        asinList.add("B09W7P5MT4");
        asinList.add("B08861XCML");
        asinList.add("B098H1K2KG");
        asinList.add("B01M0H5RDT");
        asinList.add("B0B157SNWG");
        asinList.add("B0CCVJP65R");
        asinList.add("B0C5J75TJF");
        asinList.add("B0BVQTJMZZ");
        asinList.add("B0CG2WCBDH");
        asinList.add("B0B127GW4D");
        asinList.add("B09KMYQB9T");
        asinList.add("B0CHXK8YKT");
        asinList.add("B0BDKHTWPM");
        asinList.add("B0BGLD6XNS");
        asinList.add("B08X7JYYFB");
        asinList.add("B0C7G5MC2Y");
        asinList.add("B08BX11YQB");
        asinList.add("B08X7HRRVD");
        asinList.add("B0B8DS3F9L");
        asinList.add("B0CJWFW1M2");
        asinList.add("B0BBDDWSJ9");
        asinList.add("B07QB4FG6B");
        asinList.add("B0BZ8HHTFV");
        asinList.add("B0CJWDW9LS");
        asinList.add("B0B8DK8388");
        asinList.add("B08G1T1CYZ");
        asinList.add("B08X1LWTKL");
        asinList.add("B098WVKF19");
        asinList.add("B08KHT2HDT");
        asinList.add("B0BJ6JJKLY");
        asinList.add("B08VDJ888B");
        asinList.add("B084PKN8M9");
        asinList.add("B00ID6JQ1M");
        asinList.add("B09W9JXFPV");
        asinList.add("B09V12VJ21");
        asinList.add("B0BW8MBQTT");
        asinList.add("B09JKYMG5F");
        asinList.add("B0BHHTZD6R");
        asinList.add("B0BYWMLVG1");
        asinList.add("B08ZDVCVPB");
        asinList.add("B0CHXF596M");
        asinList.add("B09GS2ZTLJ");
        asinList.add("B01MTB55WH");
        asinList.add("B0CBZNJMMN");
        asinList.add("B0C98YYRQS");
        asinList.add("B07NPN3H25");
        asinList.add("B09NHSQ68K");
        asinList.add("B09NKSGNZ5");
        asinList.add("B0CCRZPKR1");
        asinList.add("B08VDGMBGP");
        asinList.add("B0BW8KDDFK");
        asinList.add("B09S37RB69");
        asinList.add("B0D5483BFB");
        asinList.add("B09V968CP3");
        asinList.add("B0BDJW7V2V");
        asinList.add("B0CN6RGZM5");
        asinList.add("B083X3D2FY");
        asinList.add("B0BQ6SYQWL");
        asinList.add("B0BFRQZ9FL");
        asinList.add("B099K5HP9Z");
        asinList.add("B09Y2MYL5C");
        asinList.add("B0CHFMLNCY");
        asinList.add("B09WVWSGMX");
        asinList.add("B09YVHZNRH");
        asinList.add("B0CZ6WM2LG");
        asinList.add("B0CN734SG8");
        asinList.add("B08GHCJ3S6");
        asinList.add("B07VGBR5V5");
        asinList.add("B08XBMKC3D");
        asinList.add("B01MRFH8RY");
        asinList.add("B096KP3J3K");
        asinList.add("B08SC1QDQT");
        asinList.add("B096MN43JB");
        asinList.add("B00EQ16666");
        asinList.add("B0C5D5SZ38");
        asinList.add("B0C4Q7C2Q4");
        asinList.add("B09TCC4PMT");
        asinList.add("B09TR9BK2T");
        asinList.add("B09HJHSLRV");
        asinList.add("B08T7H2FQ2");
        asinList.add("B082FXD9DW");
        asinList.add("B09TRCWFKT");
        asinList.add("B0BWJH33HJ");
        asinList.add("B09D3M1S43");
        asinList.add("B0CLR68DVS");
        asinList.add("B01HTTQ6A2");
        asinList.add("B09FJ1TPBY");
        asinList.add("B08GH9ZVRK");
        asinList.add("B07N954Q3S");
        asinList.add("B07MXQ1ZTM");
        asinList.add("B082HPWBWX");
        asinList.add("B0BLH7BZ9Z");
        asinList.add("B08TM7HJN1");
        asinList.add("B0BTZ11QYL");
        asinList.add("B002SN9T0E");
        asinList.add("B083W1MXMM");
        asinList.add("B0B9SN1B19");
        asinList.add("B09B9YB6WN");
        asinList.add("B07HWT651P");
        asinList.add("B09PY1WMLN");
        asinList.add("B07FYDGD7R");
        asinList.add("B078YZ2XBF");
        asinList.add("B07PRYNS9L");
        asinList.add("B00FBN9H64");
        asinList.add("B00F9KODRC");
        asinList.add("B099NQY4N7");
        asinList.add("B0CNQ6MGMX");
        asinList.add("B09ZVH5V2W");
        asinList.add("B08TM5YD2L");
        asinList.add("B0BD5HQH15");
        asinList.add("B0BCLH55PR");
        asinList.add("B0BZDJLCH6");
        asinList.add("B0BY9KGZMF");
        asinList.add("B07MY4WCLG");
        asinList.add("B08TM3GMXJ");
        asinList.add("B0BG3BLM12");
        asinList.add("B012SG8AQE");
        asinList.add("B0CFQB7KH9");
        asinList.add("B08KP829ZV");
        asinList.add("B08GMD5KVC");
        asinList.add("B07NWYJCNB");
        asinList.add("B08GMC4TYR");
        asinList.add("B06Y251PJS");
        asinList.add("B0BC9QKR3S");
        asinList.add("B08KHLWHH9");
        asinList.add("B08Y93H17Q");
        asinList.add("B09BV7G4CN");
        asinList.add("B09PVKNMWY");
        asinList.add("B091DJ5VY8");
        asinList.add("B08D9T9831");
        asinList.add("B0851FNS1S");
        asinList.add("B09L3XBXQ5");
        asinList.add("B0C64WJFB7");
        asinList.add("B08XY9P31L");
        asinList.add("B07PML7H3P");
        asinList.add("B07SQ2FZTK");
        asinList.add("B00UTBFWNU");
        asinList.add("B0CSZT69P9");
        asinList.add("B0BG39JGL5");
        asinList.add("B06XRZRPCY");
        asinList.add("B0C9MXDY7K");
        asinList.add("B09TR89SM9");
        asinList.add("B086XNM37Q");
        asinList.add("B0C8TBTLFW");
        asinList.add("B09RT8GHD2");
        asinList.add("B07MXNKSMH");
        asinList.add("B08NSS1G6K");
        asinList.add("B0CF2F7T69");
        asinList.add("B09K44B9MW");
        asinList.add("B0BG3BXKV5");
        asinList.add("B07N93RJ9M");
        asinList.add("B09K45DS9W");
        asinList.add("B0048SVZC2");
        asinList.add("B09BV7K9P9");
        asinList.add("B0C1SMTC3D");
        asinList.add("B0CF2J1VKR");
        asinList.add("B09TR7SRV4");
        asinList.add("B09L36W3F2");
        asinList.add("B09RWXY7YP");
        asinList.add("B0BQ7715WG");
        asinList.add("B08PBKHDZG");
        asinList.add("B091B6XN6F");
        asinList.add("B089DBJGMS");
        asinList.add("B07F2X3L99");
        asinList.add("B08GN8SK39");
        asinList.add("B08YNWLXFL");
        asinList.add("B0BG3BHXSJ");
        asinList.add("B09FQFZ3MV");
        asinList.add("B08ZHM8FC1");
        asinList.add("B07DPSSS6P");
        asinList.add("B072FNYLQ1");
        asinList.add("B07122RFG8");
        asinList.add("B01N540TLO");
        asinList.add("B01HV8AWXI");
        asinList.add("B09HCGGDQD");
        asinList.add("B09CDBWKJJ");
        asinList.add("B0BC9TDZ4Q");
        asinList.add("B0BC9X56C4");
        asinList.add("B08HVB386J");
        asinList.add("B093S84R46");
        asinList.add("B0BQ7BHFH7");
        asinList.add("B08GMD6TMC");
        asinList.add("B0BD84K8FC");
        asinList.add("B01BO5K8BA");
        asinList.add("B0C6M7G431");
        asinList.add("B005LYJGQY");
        asinList.add("B09MKPDJRT");
        asinList.add("B0BSZY3M5P");
        asinList.add("B09WYXZXZV");
        asinList.add("B07D1BXKYY");
        asinList.add("B093WGG34J");
        asinList.add("B0000ACOV0");
        asinList.add("B07DPWW8D8");
        asinList.add("B0B56F5QZT");
        asinList.add("B07KX1N3XZ");
        asinList.add("B07TZD3PFX");
        asinList.add("B0BG37K4FX");
        asinList.add("B09RT85VZP");
        asinList.add("B09WWLMMYP");
        asinList.add("B09TR7MY19");
        asinList.add("B08WPT9PXK");
        asinList.add("B0BZVWK27P");
        asinList.add("B09X3MPYY8");
        asinList.add("B0BL3QMPZ8");
        asinList.add("B0BG3F6Q7N");
        asinList.add("B0BV7BYFWG");
        asinList.add("B09BV8NTW1");
        asinList.add("B0D46KNWL3");
        asinList.add("B09GVXJ7X1");
        asinList.add("B0CT3P61S5");
        asinList.add("B096DPWSW6");
        asinList.add("B0BFRQQ18W");
        asinList.add("B0BHKTDP8X");
        asinList.add("B07R2DQLV3");
        asinList.add("B084TLRSCQ");
        asinList.add("B09K45QGV4");
        asinList.add("B09Q33ZRD2");
        asinList.add("B005QMCYWO");
        asinList.add("B09P6MQRG8");
        asinList.add("B09BV9F6TK");
        asinList.add("B00710A3DQ");
        asinList.add("B07PQT59F7");
        asinList.add("B09GVVMNHS");
        asinList.add("B09GVYWMDP");
        asinList.add("B08TMDN64Y");
        asinList.add("B09XMMT7M9");
        asinList.add("B07F3DFLJB");
        asinList.add("B00DN968H4");
        asinList.add("B0BDGMSX74");
        asinList.add("B08HKCVQFF");
        asinList.add("B09CDVCD23");
        asinList.add("B082PWGGMD");
        asinList.add("B0BD5RLXJ4");
        asinList.add("B09B9YT3KF");
        asinList.add("B0B6GKQLK5");
        asinList.add("B0897W1Q6D");
        asinList.add("B08GMDJXK7");
        asinList.add("B0CP5G4QMT");
        asinList.add("B09K435GWW");
        asinList.add("B09R4Q224B");
        asinList.add("B098X83YV7");
        asinList.add("B0927P8JLN");
        asinList.add("B07J5Q14B6");
        asinList.add("B082BC81VH");
        asinList.add("B0BYP5951Q");
        asinList.add("B092MFFGKY");
        asinList.add("B0CS219BQB");
        asinList.add("B099NPC5K5");
        asinList.add("B0C2QPWVQ1");
        asinList.add("B0B4P6D18K");
        asinList.add("B09K447JJY");
        asinList.add("B09LR51BJ9");
        asinList.add("B09BV7VG8L");
        asinList.add("B08CXZJWM9");
        asinList.add("B009KCFHAW");
        asinList.add("B08QMKNBK7");
        asinList.add("B082DNX9Z4");
        asinList.add("B0BV9ZRFWD");
        asinList.add("B01EZAA0PU");
        asinList.add("B0BS3YHYHW");
        asinList.add("B07F3DC75L");
        asinList.add("B07CQ4WPTN");
        asinList.add("B005OQEK9W");
        asinList.add("B009I4HQVU");
        asinList.add("B0001D1QOK");
        asinList.add("B08JPWRSL3");
        asinList.add("B06XRDTQFP");
        asinList.add("B01N5QOF5F");
        asinList.add("B00SYVSZUE");
        asinList.add("B07D3YQQKD");
        asinList.add("B0CDXW6CPB");
        asinList.add("B0B3J3Q9RD");
        asinList.add("B00GGX4U56");
        asinList.add("B09MZ738MZ");
        asinList.add("B07HLC4QLM");
        asinList.add("B07L321T61");
        asinList.add("B001NBOOSE");
        asinList.add("B079GW7H9V");
        asinList.add("B09T3L346B");
        asinList.add("B07HLBR98S");
        asinList.add("B077ZKKBFM");
        asinList.add("B08W558TS7");
        asinList.add("B07D41DLFG");
        asinList.add("B0B76939FS");
        asinList.add("B0963NZ13Y");
        asinList.add("B06XRFXDZ4");
        asinList.add("B0816XBGB1");
        asinList.add("B00319T9JU");
        asinList.add("B0007VHJ7E");
        asinList.add("B09J1DPFLM");
        asinList.add("B083Y1D8WB");
        asinList.add("B09Z2CT9SL");
        asinList.add("B0BW4LG5KS");
        asinList.add("B07HLC5QL9");
        asinList.add("B07N9F1FV8");
        asinList.add("B0713TKV32");
        asinList.add("B0087OTTB2");
        asinList.add("B009I4HRDW");
        asinList.add("B086XYFJ3J");
        asinList.add("B07D41RLSP");
        asinList.add("B06XQJMZFK");
        asinList.add("B002CZ54H0");
        asinList.add("B07N9G6KMD");
        asinList.add("B01BU0GEXK");
        asinList.add("B08XQN497G");
        asinList.add("B07CXWSVSZ");
        asinList.add("B08WRC6V8X");
        asinList.add("B084JZY2HX");
        asinList.add("B0BYJYW1Q5");
        asinList.add("B07WVTWY6B");
        asinList.add("B07RQ8FN48");
        asinList.add("B088RFW9MY");
        asinList.add("B09MKLWH7Z");
        asinList.add("B09HZYV2GS");
        asinList.add("B0C861NC3Q");
        asinList.add("B07D3YX3N4");
        asinList.add("B07HL9P2JV");
        asinList.add("B07HL6P39M");
        asinList.add("B015EPVB1W");
        asinList.add("B07L9QHM6Y");
        asinList.add("B01LDZYLJ6");
        asinList.add("B0B1V79DGP");
        asinList.add("B07GFFG1BQ");
        asinList.add("B01M3SPEZF");
        asinList.add("B01F9Y7WMK");
        asinList.add("B0097D2FGI");
        asinList.add("B08GQ7WQ86");
        asinList.add("B0876JJHZ1");
        asinList.add("B087XP5R81");
        asinList.add("B0BLP6J2GV");
        asinList.add("B0BBLW4LMB");
        asinList.add("B002L4596I");
        asinList.add("B0954RWHX4");
        asinList.add("B0BFBMTMGZ");
        asinList.add("B00LHX6LS4");
        asinList.add("B06WV9XP3S");
        asinList.add("B07C461RFP");
        asinList.add("B0B6G115ZF");
        asinList.add("B09J5C4JB9");
        asinList.add("B01GULTSSW");
        asinList.add("B0B775CW58");
        asinList.add("B086B5K44R");
        asinList.add("B0001D1QAE");
        asinList.add("B07GSD93Q8");
        asinList.add("B001TJ4GPQ");
        asinList.add("B001EQAE46");
        asinList.add("B00HT95ABE");
        asinList.add("B000K2PF4Y");
        asinList.add("B0098J4C4E");
        asinList.add("B0B4S8QZ8K");
        asinList.add("B093ZS8M48");
        asinList.add("B01MU2NXXB");
        asinList.add("B07WJ4CDKL");
        asinList.add("B01K1OAD3S");
        asinList.add("B07VTW2DY5");
        asinList.add("B01276DFC4");
        asinList.add("B01BU0GIGS");
        asinList.add("B0BRKQ7DSX");
        asinList.add("B0816XJ9F5");
        asinList.add("B001TJAI6M");
        asinList.add("B00B0VCIFS");
        asinList.add("B07FYMGSVQ");
        asinList.add("B01N7K7QQK");
        asinList.add("B07QP9VT7P");
        asinList.add("B004ULLZ9K");
        asinList.add("B082TD4R4L");
        asinList.add("B003A67LVW");
        asinList.add("B00R0Z7TFM");
        asinList.add("B07HL7BKMB");
        asinList.add("B08W56FL5Y");
        asinList.add("B071W9DH4S");
        asinList.add("B018YPFM4Q");
        asinList.add("B003ASAF7M");
        asinList.add("B0BYQRDVDK");
        asinList.add("B0748MBGXX");
        asinList.add("B08C1YMG56");
        asinList.add("B0CBMGHSCS");
        asinList.add("B001P47JJK");
        asinList.add("B005ERFK9U");
        asinList.add("B0CY4LGG6W");
        asinList.add("B084K15LGY");
        asinList.add("B001IBOPWE");
        asinList.add("B07FR78X16");
        asinList.add("B07Z41S8MF");
        asinList.add("B0866N6H3M");
        asinList.add("B01LXR2JKU");
        asinList.add("B087X9MS6K");
        asinList.add("B09QJ3H9JG");
        asinList.add("B0156XHE90");
        asinList.add("B082D3BHVW");
        asinList.add("B0B8SPBJJD");
        asinList.add("B08DJ3C9K2");
        asinList.add("B07CGXBRJ6");
        asinList.add("B09VPV3NZD");
        asinList.add("B0CF7SJSX2");
        asinList.add("B07BTCC1WV");
        asinList.add("B08LQHQNL7");
        asinList.add("B07CSJ85L7");
        asinList.add("B07QC3CH2J");
        asinList.add("B01MTVW4PU");
        asinList.add("B084QF675N");
        asinList.add("B08CVT3QKL");
        asinList.add("B08FMXG3LW");
        asinList.add("B0B8SPYJ54");
        asinList.add("B08SVPV2WL");
        asinList.add("B00GNWR0I4");
        asinList.add("B00IYEEXR0");
        asinList.add("B0BW4LKV5H");
        asinList.add("B0BLP4G9NN");
        asinList.add("B07RXZHZT1");
        asinList.add("B09XFR6N12");
        asinList.add("B09FXSPDLL");
        asinList.add("B07PBLKXYV");
        asinList.add("B0BKLPF6FX");
        asinList.add("B08THSCPCQ");
        asinList.add("B0BKLRT453");
        asinList.add("B08THL4TF5");
        asinList.add("B083F6RDRF");
        asinList.add("B09Q62SZF6");
        asinList.add("B0B5DZXY95");
        asinList.add("B08THWTMTJ");
        asinList.add("B0BHDWRD69");
        asinList.add("B08THL9S1G");
        asinList.add("B09Q634W33");
        asinList.add("B07P7B2XHT");
        asinList.add("B07PBN67YJ");
        asinList.add("B09X1SC626");
        asinList.add("B0CBTDZQH2");
        asinList.add("B09X1QFLY1");
        asinList.add("B08THWD4BN");
        asinList.add("B085V52MVK");
        asinList.add("B0CNTWMXCT");
        asinList.add("B0C7CWB74L");
        asinList.add("B07JW4TL96");
        asinList.add("B0052AXWWG");
        asinList.add("B09CWDSLZ2");
        asinList.add("B08THT6G9P");
        asinList.add("B08MQ2VNTV");
        asinList.add("B0CBTG7NN7");
        asinList.add("B07HXVS24V");
        asinList.add("B09X1SHRMQ");
        asinList.add("B08BCSLJBC");
        asinList.add("B08THRXHKS");
        asinList.add("B07RCNF77F");
        asinList.add("B07RB7TJKJ");
        asinList.add("B0CNTWB8KX");
        asinList.add("B008CDT4OK");
        asinList.add("B08THQ7LZC");
        asinList.add("B07JBN39M2");
        asinList.add("B08THY3HKR");
        asinList.add("B0CP9Z56SW");
        asinList.add("B09X1QH5Z1");
        asinList.add("B0CNTW8B7M");
        asinList.add("B09Q632DB1");
        asinList.add("B07JCGZFJ1");
        asinList.add("B07T9NWGKK");
        asinList.add("B08THT4FHH");
        asinList.add("B072X3M151");
        asinList.add("B07JQW6HBL");
        asinList.add("B09X1MHRMC");
        asinList.add("B0CZ7HZ64S");
        asinList.add("B07VWWY926");
        asinList.add("B008CDT6EI");
        asinList.add("B0CNTXNSRX");
        asinList.add("B08MPRDD7H");
        asinList.add("B08THSW8JD");
        asinList.add("B07K2VN5CC");
        asinList.add("B09X1TG4VT");
        asinList.add("B0BFM5TRMD");
        asinList.add("B0C7CYHW6Z");
        asinList.add("B08THVPP2T");
        asinList.add("B07KPD7T3X");
        asinList.add("B0CNTV815Y");
        asinList.add("B09X1QM6DY");
        asinList.add("B0CNTVSLNT");
        asinList.add("B00XPTJ4H8");
        asinList.add("B0C282SFNH");
        asinList.add("B083F6VMRQ");
        asinList.add("B085VLX74G");
        asinList.add("B08BCSBJCZ");
        asinList.add("B09X1R8CMX");
        asinList.add("B01DZYNGOO");
        asinList.add("B07TSYZQH2");
        asinList.add("B09X1R351H");
        asinList.add("B07HXZ2FPN");
        asinList.add("B00XPTJ4IC");
        asinList.add("B07TRG2FNL");
        asinList.add("B08BCRZCGC");
        asinList.add("B0CCJSJ88R");
        asinList.add("B099RYHB7G");
        asinList.add("B07ZS885SM");
        asinList.add("B0CFR3T1GB");
        asinList.add("B08THQXBKS");
        asinList.add("B08THRYPSK");
        asinList.add("B0814BD67J");
        asinList.add("B07P6D1QG5");
        asinList.add("B008CDT6FC");
        asinList.add("B0CNTW2G2F");
        asinList.add("B07TSYZQH3");
        asinList.add("B087SNXJYL");
        asinList.add("B07DYXGRGN");
        asinList.add("B07V7RHNVC");
        asinList.add("B07PXKN13V");
        asinList.add("B01LL96L7E");
        asinList.add("B07K2YRXLF");
        asinList.add("B08YR8CFHM");
        asinList.add("B0CBRVNZ3H");
        asinList.add("B0B6WRPZCM");
        asinList.add("B08THQTN8L");
        asinList.add("B0BWSDFK62");
        asinList.add("B082BRBNQY");
        asinList.add("B07RC8JWSM");
        asinList.add("B07KPDSR1D");
        asinList.add("B07K2VVHV4");
        asinList.add("B0CBRVGT1Z");
        asinList.add("B0BKLPD26L");
        asinList.add("B0BVG16N8J");
        asinList.add("B08871NN7V");
        asinList.add("B07KPQBKV5");
        asinList.add("B08THR8NWC");
        asinList.add("B08THQPZP1");
        asinList.add("B07GJNZB7M");
        asinList.add("B083F6VFX6");
        asinList.add("B0C4Q58XPQ");
        asinList.add("B00IERQC80");
        asinList.add("B08BCRS6N6");
        asinList.add("B08QJQD9M9");
        asinList.add("B07KPPCGBH");
        asinList.add("B0B9P4FCYG");
        asinList.add("B00C71WKLM");
        asinList.add("B0BHT2JSTN");
        asinList.add("B08BCR9W8C");
        asinList.add("B07KPDTHDN");
        asinList.add("B008CDT4NG");
        asinList.add("B008CDT6E8");
        asinList.add("B07HXWK2JT");
        asinList.add("B0BJDPDN5Z");
        asinList.add("B0D47QFF88");
        asinList.add("B0CGNG4S7X");
        asinList.add("B09X1R8YB9");
        asinList.add("B07PVDV8S9");
        asinList.add("B0CFR3RHRF");
        asinList.add("B01N0PW6X5");
        asinList.add("B0CQT5KFMG");
        asinList.add("B09R23MH51");
        asinList.add("B004KMFNUG");
        asinList.add("B08THKLS9Y");
        asinList.add("B01FRR3D36");
        asinList.add("B0814C5CJV");
        asinList.add("B08THTMBKT");
        asinList.add("B0CNTT6RL2");
        asinList.add("B07KL2G7N1");
        asinList.add("B0DB2KSVRZ");
        asinList.add("B09X1PWDV2");
        asinList.add("B01MTFQAPZ");
        asinList.add("B07YVJZJYW");
        asinList.add("B077Y731XS");
        asinList.add("B00XPTJ4JG");
        asinList.add("B077Y1YSTJ");
        asinList.add("B07WKNF55Z");
        asinList.add("B08L9GKZSM");
        asinList.add("B07D7WBNDL");
        asinList.add("B07GG98LNP");
        asinList.add("B09QQZC8ZX");
        asinList.add("B009ZOER92");
        asinList.add("B09XR9K9X9");
        asinList.add("B09NYD7173");
        asinList.add("B0BF59HN2Q");
        asinList.add("B075JNQK46");
        asinList.add("B07FSBH6XY");
        asinList.add("B08HRK49RF");
        asinList.add("B0822Z2PQF");
        asinList.add("B0C28BY8NL");
        asinList.add("B08HRDCQ15");
        asinList.add("B0BZ7YBGW7");
        asinList.add("B0CJYJ45TS");
        asinList.add("B074WDYBS6");
        asinList.add("B0C2J8DQC1");
        asinList.add("B0B9LBM61Q");
        asinList.add("B097PLZB7M");
        asinList.add("B0828JD1WF");
        asinList.add("B08HRH72YJ");
        asinList.add("B07DM8QD2B");
        asinList.add("B0843GY3VW");
        asinList.add("B0C2877GJS");
        asinList.add("B088M3XJN4");
        asinList.add("B0CJYJLB32");
        asinList.add("B0CR4CC5R5");
        asinList.add("B0847B6B98");
        asinList.add("B099NJZMWN");
        asinList.add("B07Z64Z4ZC");
        asinList.add("B073ZGBKHW");
        asinList.add("B07XJYGCX6");
        asinList.add("B0743KRM1P");
        asinList.add("B0BBGY8KVB");
        asinList.add("B079RRVLGQ");
        asinList.add("B08DVGFQQR");
        asinList.add("B0CJYHCPSL");
        asinList.add("B07NX6SRGL");
        asinList.add("B07CDP2ZJL");
        asinList.add("B094WBG2MJ");
        asinList.add("B07MNT79M4");
        asinList.add("B0B51CWCN7");
        asinList.add("B07F6C257T");
        asinList.add("B0799BJTFG");
        asinList.add("B073ZDGXJF");
        asinList.add("B0CR4CQDL2");
        asinList.add("B088DVJF3B");
        asinList.add("B08HRH5LWP");
        asinList.add("B09DGJ4WXH");
        asinList.add("B07481LSXS");
        asinList.add("B073ZG6YHR");
        asinList.add("B0C289HC3M");
        asinList.add("B0B1VS4BZD");
        asinList.add("B07CTTKWNN");
        asinList.add("B0BMKD1HG7");
        asinList.add("B0B9RQB3NQ");
        asinList.add("B089F3W17W");
        asinList.add("B0C2J8XTYY");
        asinList.add("B0BPCS7PGZ");
        asinList.add("B09C911Q87");
        asinList.add("B07B8LBLRB");
        asinList.add("B07B598ZHX");
        asinList.add("B07NXC33TM");
        asinList.add("B09QQQSP79");
        asinList.add("B07XHBGV7T");
        asinList.add("B0B51F586W");
        asinList.add("B09HSB9YTW");
        asinList.add("B006J1SA6A");
        asinList.add("B0CG6TB95V");
        asinList.add("B08R5CNBZW");
        asinList.add("B07NH1PYXZ");
        asinList.add("B08DND6M4T");
        asinList.add("B006J1SADS");
        asinList.add("B0CJYH3PJ8");
        asinList.add("B06XQM2TWB");
        asinList.add("B07PZHZY4V");
        asinList.add("B0C3W6G6YK");
        asinList.add("B09V247XGV");
        asinList.add("B08GLX6JN5");
        asinList.add("B0CL4QLF43");
        asinList.add("B081RM4KC9");
        asinList.add("B01M4MK8TQ");
        asinList.add("B0822YJSLS");
        asinList.add("B0949FZL65");
        asinList.add("B07ZNVZTWW");
        asinList.add("B08G9B1JQ3");
        asinList.add("B0BF56CP9J");
        asinList.add("B07CZKH8PK");
        asinList.add("B09LQS7JKG");
        asinList.add("B0B4PJ26DB");
        asinList.add("B08J4NMBL2");
        asinList.add("B0B515Z52M");
        asinList.add("B0B7SHJG4G");
        asinList.add("B07X8VQM9Y");
        asinList.add("B004JQOJ08");
        asinList.add("B00W505KWQ");
        asinList.add("B087VM4TW9");
        asinList.add("B0B5192LBN");
        asinList.add("B092K24KZ9");
        asinList.add("B099KQ5WDW");
        asinList.add("B00UH9VGH0");
        asinList.add("B08V1R73H9");
        asinList.add("B0C3VVMQ85");
        asinList.add("B0CFVZ74KT");
        asinList.add("B09QFJSNJW");
        asinList.add("B09BNWXDXH");
        asinList.add("B08WX4YRK7");
        asinList.add("B0BRB7Z8JS");
        asinList.add("B07CN78V49");
        asinList.add("B0843D6L35");
        asinList.add("B08R7MMCCK");
        asinList.add("B08WWZG8T3");
        asinList.add("B07FNN147J");
        asinList.add("B08WWTVMNZ");
        asinList.add("B08G4KJGG3");
        asinList.add("B0BV7BYNYD");
        asinList.add("B09QFS26GM");
        asinList.add("B0BV7C9VQQ");
        asinList.add("B0BRB6NFQJ");
        asinList.add("B09BNYBN8B");
        asinList.add("B08WXCF2SL");
        asinList.add("B0BBRXC9HN");
        asinList.add("B09BNV7VS1");
        asinList.add("B0813RJRYC");
        asinList.add("B07CJLPW45");
        asinList.add("B08WX6Z1VZ");
        asinList.add("B09QLJJ1PX");
        asinList.add("B0CWH1RMBZ");
        asinList.add("B0BBSMBL9S");
        asinList.add("B0CL1D81LN");
        asinList.add("B07W8Y84BY");
        asinList.add("B0BVMRHP6X");
        asinList.add("B004E9MGKK");
        asinList.add("B085R3Q5HC");
        asinList.add("B00008D0TQ");
        asinList.add("B09XGF8Z3Y");
        asinList.add("B08B267XM5");
        asinList.add("B0BVMQTL68");
        asinList.add("B09RSFPG1Z");
        asinList.add("B07CH9XWHR");
        asinList.add("B003JSEGNC");
        asinList.add("B00WN2BY7G");
        asinList.add("B0060OMXUA");
        asinList.add("B01BPHAD1W");
        asinList.add("B079XX76RM");
        asinList.add("B0C8YS6115");
        asinList.add("B07N1W36GB");
        asinList.add("B0C8YTHVKL");
        asinList.add("B07GWS4BSJ");
        asinList.add("B0025YVBG6");
        asinList.add("B017ROO5TS");
        asinList.add("B004SBLR4U");
        asinList.add("B01DA53DAU");
        asinList.add("B0BWSJGBHW");
        asinList.add("B000JQFX1G");
        asinList.add("B0B7MSGBX1");
        asinList.add("B0117DNDXY");
        asinList.add("B003DZBRRY");
        asinList.add("B06X1B328F");
        asinList.add("B000EIA0LW");
        asinList.add("B07YRYK8P8");
        asinList.add("B09GM9FP5K");
        asinList.add("B09YMZZ983");
        asinList.add("B0B7NW66GT");
        asinList.add("B0736LN8BV");
        asinList.add("B0BS9QPN3W");
        asinList.add("B09C64HBQX");
        asinList.add("B0BV11X1YQ");
        asinList.add("B01487C6WA");
        asinList.add("B0BL7G41LH");
        asinList.add("B07FSZQK27");
        asinList.add("B0CFLKK7QS");
        asinList.add("B0BQ2SKG18");
        asinList.add("B08DBLYVKT");
        asinList.add("B0BL1PYL4Z");
        asinList.add("B098TVZ6TS");
        asinList.add("B0BCW1S7XR");
        asinList.add("B095CLQ1PT");
        asinList.add("B09WVZ25WL");
        asinList.add("B093C8S6B1");
        asinList.add("B07XLML2YS");
        asinList.add("B091J94FMC");
        asinList.add("B083V41T6M");
        asinList.add("B00ENZRQH8");
        asinList.add("B01HTGBF4M");
        asinList.add("B07JW4CMW3");
        asinList.add("B07JCC7P1L");
        asinList.add("B01HTGB556");
        asinList.add("B07LBD6P5P");
        asinList.add("B07JB9D3BS");
        asinList.add("B0CMHMYFW7");
        asinList.add("B0C1CSSRJX");
        asinList.add("B07JW4SYK4");
        asinList.add("B07J9KKMFD");
        asinList.add("B07K8YDLT1");
        asinList.add("B07JDBSMVP");
        asinList.add("B01CE3D2DM");
        asinList.add("B07MCVYNDC");
        asinList.add("B01GD0KZSC");
        asinList.add("B0005Z6ZK4");
        asinList.add("B078GP5VN3");
        asinList.add("B09CLWYM52");
        asinList.add("B01G7F3UGC");
        asinList.add("B07MY6SYTZ");
        asinList.add("B08R9ZZ56X");
        asinList.add("B0BYFTYJD8");
        asinList.add("B08NDFBJ2N");
        asinList.add("B09RG3D3V4");
        asinList.add("B088M15V6T");
        asinList.add("B08X4NSRTV");
        asinList.add("B0B51RTWGK");
        asinList.add("B08QVJBRJR");
        asinList.add("B08TWW3SBZ");
        asinList.add("B088LZX4PC");
        asinList.add("B07J5GLXFK");
        asinList.add("B08YJTBB55");
        asinList.add("B0B51GPHMX");
        asinList.add("B0881MKMRL");
        asinList.add("B092T2P2D3");
        asinList.add("B0BTR1QMJL");
        asinList.add("B08L8WK7FG");
        asinList.add("B09CLY36C7");
        asinList.add("B08YJT2164");
        asinList.add("B09RG7QNBL");
        asinList.add("B09R7VVMX8");
        asinList.add("B07MBTHRQM");
        asinList.add("B08XZHFBTY");
        asinList.add("B09CLX822G");
        asinList.add("B0784WV1F8");
        asinList.add("B01M179NN1");
        asinList.add("B0BC6PQ86C");
        asinList.add("B09R7S954R");
        asinList.add("B09CLXYJVJ");
        asinList.add("B08X4MRQ8B");
        asinList.add("B08PW5VDLN");
        asinList.add("B07MQLL25F");
        asinList.add("B08TWTMWH8");
        asinList.add("B07667KLLW");
        asinList.add("B09D3D235P");
        asinList.add("B08R9YPHVJ");
        asinList.add("B08B4Z3H6M");
        asinList.add("B099MQ35T2");
        asinList.add("B09DKXR9BB");
        asinList.add("B08XZJMHP4");
        asinList.add("B0CBRTZB7P");
        asinList.add("B0C69MWNRW");
        asinList.add("B0CBRVL8MD");
        asinList.add("B07NX1PC1Y");
        asinList.add("B0CCW6K42T");
        asinList.add("B083HKL8C6");
        asinList.add("B0CFYGMXJY");
        asinList.add("B0C5Y387PW");
        asinList.add("B0BLZG1B9J");
        asinList.add("B08B8F63XP");
        asinList.add("B0C37WZKQ6");
        asinList.add("B0BJFJS7NY");
        asinList.add("B0C8XFWV3P");
        asinList.add("B0C8X8DW5D");
        asinList.add("B0C37VR23X");
        asinList.add("B0C5Y4J6R1");
        asinList.add("B0CFYGKFP3");
        asinList.add("B0CFYH7TLD");
        asinList.add("B0CDWZSTT8");
        asinList.add("B09VTDHVDN");
        asinList.add("B078DDZLCV");
        asinList.add("B0BJQKKX22");
        asinList.add("B078WG5P4W");
        asinList.add("B0C37WYQT9");
        asinList.add("B07ZHSVMWW");
        asinList.add("B0CGHWP4M8");
        asinList.add("B0BJFG465L");
        asinList.add("B0CGHX9F73");
        asinList.add("B0C5Y3B4GD");
        asinList.add("B0C8ZJ3VH3");
        asinList.add("B084DSJTBD");
        asinList.add("B07KW4K15Z");
        asinList.add("B08NK9ZJ96");
        asinList.add("B084DS8WHH");
        asinList.add("B07BVRJR2P");
        asinList.add("B07G36P8HK");
        asinList.add("B07L8KLS1S");
        asinList.add("B0B61C4L9Z");
        asinList.add("B07DGL1YJC");
        asinList.add("B07FPGW68G");
        asinList.add("B08W1VRCV5");
        asinList.add("B091YL5PGV");
        asinList.add("B09XR7RXCW");
        asinList.add("B0BGMPFXXL");
        asinList.add("B07CJLT5FW");
        asinList.add("B0B1N168N8");
        asinList.add("B07CKGQSDS");
        asinList.add("B07CN57CN4");
        asinList.add("B09JPD5C1J");
        asinList.add("B01N9ZANEV");
        asinList.add("B01N65E633");
        asinList.add("B01N2IEKCY");
        asinList.add("B01MRLZ9T1");
        asinList.add("B016R0KIGM");
        asinList.add("B014GNJWW8");
        asinList.add("B01MQKN1QK");
        asinList.add("B014GNJYFS");
        asinList.add("B016R0KO5C");
        asinList.add("B016R0KGTQ");
        asinList.add("B014GNJTMQ");
        asinList.add("B016R0KJC0");
        asinList.add("B014GNJQLK");
        asinList.add("B014GNJV6K");
        asinList.add("B014GNK1M8");
        asinList.add("B09K31KK9B");
        asinList.add("B016R0KNBM");
        asinList.add("B01N95NVS0");
        asinList.add("B00KWK8TT2");
        asinList.add("B00GUXJRYG");
        asinList.add("B00GUXJSMM");
        asinList.add("B0CLV34JJX");
        asinList.add("B00KOJT7UG");
        asinList.add("B00KWK8R80");
        asinList.add("B00KOJT7WE");
        asinList.add("B00GUXJT6M");
        asinList.add("B0CW3J8Z5H");
        asinList.add("B09643Z6YS");
        asinList.add("B00KOJT4ZE");
        asinList.add("B0CW3JLL4B");
        asinList.add("B08FBL43QC");
        asinList.add("B0CLV27QJP");
        asinList.add("B01N42HVS6");
        asinList.add("B002LITTDI");
        asinList.add("B01N9JGP9R");
        asinList.add("B08BBXLBS1");
        asinList.add("B01N42HX6E");
        asinList.add("B09KCFYSJH");
        asinList.add("B01J1LQ188");
        asinList.add("B00KWFGYOO");
        asinList.add("B00KWF4GLW");
        asinList.add("B01ESD63ZA");
        asinList.add("B0725RV7G2");
        asinList.add("B0CLV1C79G");
        asinList.add("B014GNJNBI");
        asinList.add("B09PPRY8NS");
        asinList.add("B0CN343C61");
        asinList.add("B0CW3K5W99");
        asinList.add("B0014C3X5C");
        asinList.add("B08FBJPSZ6");
        asinList.add("B016R0KP06");
        return asinList;
    }
}
