package com.app.fku.bim.fonksiyon.impl;

import com.app.fku.bim.entity.BimKategori;
import com.app.fku.bim.entity.BimTelegramConf;
import com.app.fku.bim.fonksiyon.service.BimGenelService;
import com.app.fku.bim.fonksiyon.service.BimUrunToplaFonksiyon;
import com.app.fku.bim.repository.BimTelegramConfRepository;
import com.app.fku.genel.fonksiyon.service.GenelService;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;

@Service
public class BimUrunToplaFonksiyonImpl implements BimUrunToplaFonksiyon {

    @Autowired
    BimGenelService bimGenelService;

    @Autowired
    GenelService genelService;

    @Autowired
    BimTelegramConfRepository bimTelegramConfRepository;

    @Override
    public HashMap<String, Long> menudenUrunBul(BimKategori bimKategori, HashMap<String, Long> urunHashMap, boolean ilkMi, HashMap<String, Long> yasakliUrunHashMap) throws IOException, InterruptedException {
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm");
        NumberFormat nf = new DecimalFormat("#0.00");

        HashMap<String, Long> yeniUrunHashMap = new HashMap<>();
        try {
            Document bimDoc = bimGenelService.urleGit(bimKategori.getSayfaAdresi());

            if (bimDoc == null) {
                throw new Exception("bimDoc null (Captcha)");
            } else {

            }

            Elements urunElementList = bimDoc.getElementsByClass("product");
            for (Element urunElement: urunElementList) {

                String urunLink = "";
                try {
                    urunLink = urunElement.childNodes().get(0).childNodes().get(0).childNodes().get(0).childNodes().get(0).attributes().get("href");
                } catch (Exception e) {}
                Element detayElement = urunElement.getElementsByClass("col-6 col-sm-12 col-lg-12 descArea").get(0);
                String markaAdi = "";
                try {
                    markaAdi = detayElement.childNodes().get(0).childNodes().get(0).toString();
                } catch (Exception e) {}
                String urunAdi = "";
                try {
                    urunAdi = detayElement.childNodes().get(1).childNodes().get(0).toString();
                } catch (Exception e) {}

                Long yasakli = yasakliUrunHashMap.get(urunLink);
                if (yasakli != null && yasakli == 1L) {
                    continue;
                }

                String fiyatStr = detayElement.getElementsByClass("gButton triangle").get(0).getElementsByClass("text quantify").get(0).childNodes().get(0).toString().trim().replace(",", "").replace(".", "");

                Long yeniFiyat = new Long(fiyatStr);
                Long eskiFiyat = urunHashMap.get(urunLink);

                if (eskiFiyat == null) {
                    //yeni gelmiş ürün
                    yeniUrunHashMap.put(urunLink, yeniFiyat);
                    if (!ilkMi) {
                        //mesaj at
                        String akakceLink = urunAdi.replace(" ", "%2B");
                        akakceLink = akakceLink.replace("+", "");

                        String mesaj = "" +
                                "YENİ ÜRÜN%0A" +
                                "Ürün Adı: " + markaAdi + " - " + urunAdi + "%0A" +
                                "Yeni Fiyat: " + nf.format(yeniFiyat) + "%0A" +
                                "Ürün Link:" + "https://www.bim.com.tr/" + urunLink + "%0A" +
                                "Tarih: " + sdf.format(new Date()) + "%0A" +
                                "Akakçe Link:https://www.akakce.com/arama/?q=" + akakceLink + " %0A " +
                                "***Generated By Emin KAYABASI***";

                        telegramMesajGonder(mesaj, bimKategori, urunLink);
                    }
                } else {
                    //zaten var olan ürün
                    if (yeniFiyat < eskiFiyat) {
                        //mesaj at
                        String akakceLink = urunAdi.replace(" ", "%2B");
                        akakceLink = akakceLink.replace("+", "");

                        Long indirim = eskiFiyat - yeniFiyat;
                        String mesaj = "" +
                                "Ürün Adı: " + markaAdi + " - " + urunAdi + "%0A" +
                                "Eski Fiyat: " + nf.format(eskiFiyat) + "%0A" +
                                "Yeni Fiyat: " + nf.format(yeniFiyat) + "%0A" +
                                "İndirim: " + nf.format(indirim) + "%0A" +
                                "Ürün Link:" + "https://www.bim.com.tr/" + urunLink + "%0A" +
                                "Tarih: " + sdf.format(new Date()) + "%0A" +
                                "Akakçe Link:https://www.akakce.com/arama/?q=" + akakceLink + " %0A " +
                                "***Generated By Emin KAYABASI***";

                        telegramMesajGonder(mesaj, bimKategori, urunLink);
                    }
                    //urunHashMap.remove(urunLink);
                    yeniUrunHashMap.put(urunLink, yeniFiyat);
                }
            }
            return yeniUrunHashMap;
        } catch (Exception e) {
            System.out.println("Bim Hata Kategori:" + bimKategori.getKategoriAdi());
            StringWriter sw = new StringWriter();
            e.printStackTrace(new PrintWriter(sw));
            System.out.println(sw.toString());
            Thread.sleep(10000L);
            return yeniUrunHashMap;
        }
    }

    private void telegramMesajGonder(String mesaj, BimKategori bimKategori, String urunId) throws IOException, InterruptedException {
        List<BimTelegramConf> bimTelegramConfList = bimTelegramConfRepository.findByBimKategori(bimKategori);

        for (BimTelegramConf bimTelegramConf: bimTelegramConfList) {//fkumesajbot
            genelService.telegramMesajGonder(mesaj, bimTelegramConf.getTelegramChatId(), urunId, "5326840199:AAEWApODrhD-pxplBYAgUIRMo2FI565mNfM");
        }
    }
}
